<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Contact Information</name>
   <tag></tag>
   <elementGuidId>1d228683-a985-4e9f-a60b-ba2a41f3b6e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.accountInformation-rowSubtitle-2qL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[4]/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5b33927d-5b07-49aa-af11-ed623b49666e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accountInformation-rowSubtitle-2qL</value>
      <webElementGuid>57060302-7d58-46d1-ac72-be318cac8bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact Information</value>
      <webElementGuid>5ffc9053-1f49-4449-aedf-6492d4a69d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container grid accountDashboard-root-186&quot;]/div[@class=&quot;account-dashboard-details-root col-span-12 col-span-7--tablet col-span-8--wide accountDashboard-childrenContainer-gRs&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;account-dashboard-contact-info-root col-span-12 col-span-6--desktop accountInformation-section-1vT&quot;]/div[@class=&quot;accountInformation-accountInformationRow-2tp&quot;]/p[@class=&quot;accountInformation-rowSubtitle-2qL&quot;]</value>
      <webElementGuid>103c6909-520a-4717-99a1-6a1fa23ffe37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[4]/div/div/div/p</value>
      <webElementGuid>457e100e-a87a-4d31-9e36-3159e5c77fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[3]/following::p[1]</value>
      <webElementGuid>4a5a0765-df14-4a8d-a631-58102860c04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[2]/following::p[1]</value>
      <webElementGuid>ee6c998f-77cb-48c5-8b4a-8b1fdf15cbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John Benny'])[1]/preceding::p[1]</value>
      <webElementGuid>70c07b8a-7583-4d6d-818a-2c572da257cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::p[2]</value>
      <webElementGuid>b84208e3-b577-4168-ab2c-9f841dd2e655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Contact Information']/parent::*</value>
      <webElementGuid>96c5dbf6-b7bf-4407-a86b-f76f2d9a8b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>7979c829-1fa8-4ca3-8017-e864290f331d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Contact Information' or . = 'Contact Information')]</value>
      <webElementGuid>6d856903-471d-43de-8b9c-0fc02a205687</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
