<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_John Benny</name>
   <tag></tag>
   <elementGuidId>97371990-d605-4564-87fd-96f26af3076a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.noibu-blocked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[4]/div/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cb075ce8-85bc-44fd-b537-0e82ffb3b21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noibu-blocked</value>
      <webElementGuid>e79060d4-2923-45bf-8de8-4929b2d62284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>John Benny</value>
      <webElementGuid>c5f404e4-16db-4be2-93ca-1cd31de47d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container grid accountDashboard-root-186&quot;]/div[@class=&quot;account-dashboard-details-root col-span-12 col-span-7--tablet col-span-8--wide accountDashboard-childrenContainer-gRs&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;account-dashboard-contact-info-root col-span-12 col-span-6--desktop accountInformation-section-1vT&quot;]/div[@class=&quot;accountInformation-accountInformationRow-2tp&quot;]/div[@class=&quot;accountInformation-rowContent-3m2&quot;]/span[@class=&quot;noibu-blocked&quot;]</value>
      <webElementGuid>1fe02566-9d5c-4830-977b-f472d163625f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[4]/div/div/div/div/span</value>
      <webElementGuid>84f88a17-5c32-4e17-8392-873bc417c2e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Information'])[3]/following::span[1]</value>
      <webElementGuid>3cc0089e-0a11-4101-b547-99b660b408c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[2]/following::span[1]</value>
      <webElementGuid>c1f98178-361c-4a9a-a496-7d136d0dd41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::span[1]</value>
      <webElementGuid>3ee9eb8f-024f-41c2-a98e-9163f05a3977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='John Benny']/parent::*</value>
      <webElementGuid>0d1f2c10-0d52-4392-a938-3f9102ba594d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span</value>
      <webElementGuid>b41f20a9-b913-493d-a1b6-80949b68896a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'John Benny' or . = 'John Benny')]</value>
      <webElementGuid>3c910927-c169-41c4-bd0a-6be555e925fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
