<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_GBP_logo-logo-2KO</name>
   <tag></tag>
   <elementGuidId>1c00db22-6d2a-4043-be77-125bd3dc0121</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[3]/nav/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.logo-logo-2KO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8214c937-b4db-427e-9068-0c28feb26a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/secretSales-9Df.svg</value>
      <webElementGuid>eb295b5e-104e-478c-a44c-19f06100de0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Secret Sales UK</value>
      <webElementGuid>addcdf0b-786b-4ff2-8c8f-d05dd13d1fa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo-logo-2KO</value>
      <webElementGuid>4b8a2354-ba10-4a48-8a02-6035dba6091b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>169</value>
      <webElementGuid>cdee6540-2333-4ea9-9b92-325f5217c8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c7c93215-8178-42db-ae58-992ab4043b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/header[@class=&quot;header-root header-root-2P7&quot;]/div[@class=&quot;container header-content-BBd&quot;]/nav[@class=&quot;header-logoWrapper-1Z- visuallyHiddenUntilDesktop&quot;]/a[@class=&quot;logo-logoContainer-2Tc&quot;]/img[@class=&quot;logo-logo-2KO&quot;]</value>
      <webElementGuid>e07cb191-e0c1-4c8e-9ccc-30a95edd05c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[3]/nav/a/img</value>
      <webElementGuid>d0500aa2-0373-475a-b533-bcbbd64607e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Secret Sales UK']</value>
      <webElementGuid>5b3024fc-cdda-430c-a338-24e9d733e242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>dea6010d-deec-459d-9ecb-2e7881c9a4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/secretSales-9Df.svg' and @alt = 'Secret Sales UK']</value>
      <webElementGuid>6940a9ce-7fc5-4a13-b8cf-99849252f5f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
