<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>line</name>
   <tag></tag>
   <elementGuidId>199f64bd-763d-4512-8e56-77b6ebf55d19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>line:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>c4a5ea6d-0345-45b1-be7f-ed2b78252dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3582d448-46b8-454a-899e-3caa3b890dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>30b6b0b7-2446-4af7-8dc2-1c975121e62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y1</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>cb685d63-149d-4e31-86dc-02fb75688b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>39d11868-73d8-4925-a3ae-832085329e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeIconSvg&quot;)/line[2]</value>
      <webElementGuid>18eac0a8-cf9a-4ec8-ae6b-8bd960307c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SECRET SALES  GIFTS FOR THEM, GIFTS FO_4fd8cd/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>f5c2c9ae-04e4-4855-869f-1883a7056ed7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
