<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_12345</name>
   <tag></tag>
   <elementGuidId>a0303039-92b4-4947-8f3e-16ef9e4a9c82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1fdb9ef1-0c0f-489d-aef1-1035e7e26e7a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#1fdb9ef1-0c0f-489d-aef1-1035e7e26e7a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>de125205-5030-4822-9c0b-f4b0224490ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>a53c9d95-fe91-424a-b774-38ab51ce1800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1fdb9ef1-0c0f-489d-aef1-1035e7e26e7a</value>
      <webElementGuid>afd7348e-3e75-4eb6-910b-213d19d75d46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>ec230993-fb78-4bbf-b340-336ac46f13fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>f27da00d-99ca-4820-8e74-32e446cfbb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1fdb9ef1-0c0f-489d-aef1-1035e7e26e7a&quot;)</value>
      <webElementGuid>8c92ac31-a290-4b7f-a742-7337eb78af12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1fdb9ef1-0c0f-489d-aef1-1035e7e26e7a']</value>
      <webElementGuid>3977e6b7-86f3-42ef-9dbb-421236ae29d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/div/form/section/section/div[2]/div/span/span/select</value>
      <webElementGuid>54385c4f-58f4-48c3-b61c-0f78d3207b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::select[1]</value>
      <webElementGuid>1217f18a-a871-4073-bc51-6589f3444d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[2]</value>
      <webElementGuid>fe753667-4dd4-41f0-9aea-a5aec2258d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[1]</value>
      <webElementGuid>cb72f91a-e364-4ecd-9aee-1b8de9ea7f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::select[1]</value>
      <webElementGuid>042a12dd-6523-484b-ac57-de83bef220a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/select</value>
      <webElementGuid>59ff570d-a413-4e3f-8495-1fb055f81407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '1fdb9ef1-0c0f-489d-aef1-1035e7e26e7a' and @name = 'quantity' and (text() = '12345' or . = '12345')]</value>
      <webElementGuid>6616d5cf-e190-424c-a149-8d411b8d33c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
