<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Trousers</name>
   <tag></tag>
   <elementGuidId>f9a1601b-1fe6-49e4-930a-461585daa69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/aside[4]/div/div/div/div/div/ul/li[4]/div/ul/li[5]/div/ul/li[19]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6d98e112-f791-4851-b425-0e2e7f62c17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-mobile-nav__nav-link c-ev-attached</value>
      <webElementGuid>9ed7c277-2c13-47ac-be64-b2e3d71c953f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.secretsales.com/clothing/trousers/shop-by/gender/gender_male,gender_unisex/</value>
      <webElementGuid>5953dcd2-7f07-4b29-81e5-6d48f197b922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Trousers</value>
      <webElementGuid>b0fcecb1-891c-4e25-81d6-e17a95d772b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/aside[@class=&quot;navigation-root_open-3KH navigation-root-3v2 navigation-exit-2Xc navigation-hidden-1Ft navigation-enter-1rs navigation-visible-1M_&quot;]/div[@class=&quot;navigation-body-1TM navigation-exit-2Xc navigation-visible-1M_&quot;]/div[1]/div[@class=&quot;cmsBlock-content-_Ac&quot;]/div[1]/div[@class=&quot;html-root-2b-&quot;]/ul[@class=&quot;c-mobile-nav__categories js-mobile-nav-category c-mobile-nav__categories--hide-scrollbar&quot;]/li[4]/div[@class=&quot;c-mobile-nav__sub-nav-container&quot;]/ul[1]/li[5]/div[@class=&quot;c-mobile-nav__sub-nav-container c-mobile-nav__sub-nav-container--active&quot;]/ul[1]/li[19]/a[@class=&quot;c-mobile-nav__nav-link c-ev-attached&quot;]</value>
      <webElementGuid>ccbd37e9-3efa-41ce-a833-7e02e5a750ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/aside[4]/div/div/div/div/div/ul/li[4]/div/ul/li[5]/div/ul/li[19]/a</value>
      <webElementGuid>28de667c-79b5-49b4-93d3-5f98bf527b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Trousers')])[10]</value>
      <webElementGuid>33327b5a-80f6-4003-bb25-455c9319c66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tracksuits'])[5]/following::a[1]</value>
      <webElementGuid>a315d16a-1d5c-4d7f-af65-535f88ff6eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[7]/following::a[2]</value>
      <webElementGuid>e6f770f3-22b2-462c-b68c-827c9ca3070a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T-shirts'])[3]/preceding::a[1]</value>
      <webElementGuid>1d099a61-06cb-4a2f-b995-aeefeebe7933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underwear &amp; Socks'])[2]/preceding::a[2]</value>
      <webElementGuid>fb12a200-ed5f-47a4-af9f-ebd3b4f502b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://www.secretsales.com/clothing/trousers/shop-by/gender/gender_male,gender_unisex/')])[2]</value>
      <webElementGuid>623125ea-4207-42a1-b389-4d6ad1bae802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/ul/li[5]/div/ul/li[19]/a</value>
      <webElementGuid>eebb5113-6adb-4f82-a3e6-f4ce44662b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.secretsales.com/clothing/trousers/shop-by/gender/gender_male,gender_unisex/' and (text() = 'Trousers' or . = 'Trousers')]</value>
      <webElementGuid>7a1ef837-de62-47f9-8149-9405398ce5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
