<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>c078c149-d78d-4c32-b25b-b43749e3bd03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>d3e04e7f-4bc1-4662-bf7c-e7817d1c4183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#fff</value>
      <webElementGuid>9fa70160-e59c-4aa3-b4f0-05263f381985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M0-6.1a2.1 2.1 0 1 1 0 4.2 2.1 2.1 0 1 1 0-4.2m0 9c2.97 0 6.1 1.46 6.1 2.1v1.1H-6.1V5c0-.64 3.13-2.1 6.1-2.1M0-8a4 4 0 1 0 0 8 4 4 0 1 0 0-8zm0 9c-2.67 0-8 1.34-8 4v3H8V5c0-2.66-5.33-4-8-4z</value>
      <webElementGuid>35fda6b7-f949-4d31-97ca-00ed8fd6a597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/header[@class=&quot;header-root header-root-2P7&quot;]/div[@class=&quot;container header-content-BBd&quot;]/div[@class=&quot;header-actionsWrapper-1gF&quot;]/div[@class=&quot;header-search-bar header-secondaryActions-1if&quot;]/div[@class=&quot;header-userIconsWrapper-1bS&quot;]/div[@class=&quot;sign-in-icon-root accountChip-root-E3l&quot;]/a[@class=&quot;accountChip-link-3p0&quot;]/div[@class=&quot;accountChip-icon-xZU&quot;]/div[1]/svg[@class=&quot;injected-svg&quot;]/path[2]</value>
      <webElementGuid>0e8894df-9336-4dfe-917c-6e72ce3423ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vector-effect</name>
      <type>Main</type>
      <value>non-scaling-stroke</value>
      <webElementGuid>e846dc38-6d28-483d-93c5-6f88724db0ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>matrix(61.2627 0 0 61.2627 500.0005 500.0005)</value>
      <webElementGuid>f09745af-e20c-401e-bcba-586932409d0b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
