<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SIGN UP NOW</name>
   <tag></tag>
   <elementGuidId>2e8914bd-a57b-4d57-a035-9a1fabbca592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ctabutton1header1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctabutton1header1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3a791474-8124-44c0-8ee5-eaf4a40f264c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctabutton1header1</value>
      <webElementGuid>5393aacc-63a3-4090-a674-ed7e55a66912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#ffffff</value>
      <webElementGuid>651f4d6c-310b-434c-873b-3e27e22f0211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>1.25rem</value>
      <webElementGuid>80d4ef35-d6e5-4437-9f38-9cae6b941e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>letter-spacing</name>
      <type>Main</type>
      <value>0px</value>
      <webElementGuid>dc4d8ca3-1a68-4a3d-8080-0c6b31315ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-su8u97</value>
      <webElementGuid>da9311d6-efb8-4c72-9bf9-45f5f2fcf185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIGN UP NOW</value>
      <webElementGuid>3abeaf90-4717-4064-b7c9-a87a6100bdc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctabutton1header1&quot;)</value>
      <webElementGuid>a2ea0d8c-153b-4ca4-b81d-66947f8a2d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SECRET SALES  WHY WAIT FOR BLACK FRIDA_2098a2/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>8158b790-bfaf-424e-8359-6f900bf3d102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ctabutton1header1']</value>
      <webElementGuid>eb8bf33c-edba-44da-9974-c795652366d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ctabutton1']/div/span</value>
      <webElementGuid>d43a9860-089d-4d63-b769-7c5bdb116716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Address'])[1]/following::span[1]</value>
      <webElementGuid>8eaa6c71-d8b1-4286-8168-535e18acd557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Both'])[1]/following::span[1]</value>
      <webElementGuid>e31ecfc5-b727-4fe8-92ea-b2ef23455db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::span[1]</value>
      <webElementGuid>e5c41d63-e3b5-42b2-9617-168566ff980f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'ctabutton1header1', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>698db7ca-ade2-4cea-b0da-7969e8086304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SIGN UP NOW']/parent::*</value>
      <webElementGuid>ab9306a5-9dc9-4620-99d5-615f1164bd58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>5aeaed2c-6324-4238-9483-5c01b177b15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ctabutton1header1' and (text() = 'SIGN UP NOW' or . = 'SIGN UP NOW')]</value>
      <webElementGuid>ef5f4d63-adc4-4989-8802-a8a718671bd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
