<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Sign up today for a FREE tastecard plus_507bcf</name>
   <tag></tag>
   <elementGuidId>74301076-de80-4bcd-9fbf-3c83422748d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeIconSvg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-up for 10% OFF + beat the Black Friday rush'])[1]/preceding::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>97c48a80-ef21-44d1-8b62-9d32efc36b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeIconSvg</value>
      <webElementGuid>1083cab6-0493-4fd9-8c14-9645ca28a1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 45 45</value>
      <webElementGuid>34306bf5-d8e6-4069-8c3b-aa6d984bee3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000000</value>
      <webElementGuid>841c13dc-2876-480c-8cb6-6648334fc700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a75e7b79-f6b0-49c9-9718-be39e39305ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-oohciz</value>
      <webElementGuid>a9bc1db0-149d-4e73-8ee6-71f752820f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeIconSvg&quot;)</value>
      <webElementGuid>7033cd47-5f6b-49c4-9de6-d175e94db061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>36c65c74-1f35-4c61-8efd-e51280d6c184</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-up for 10% OFF + beat the Black Friday rush'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>e6d474e5-5dac-462b-95da-ce12f0346bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ Unmissable Black Friday deals'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>f477c2d9-c614-41db-a3f4-eef8ce8f36d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[@id = 'closeIconSvg']</value>
      <webElementGuid>b6946b5f-a9d1-487d-b80e-2e3d87594834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up today and get 15% off* plus...'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>d40c5193-7bbe-418b-af1f-33c9a6dabf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ New brand launches'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>bdafb025-13bf-4c54-88ed-4225d7b87db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up today for a FREE tastecard plus...'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>847fc26a-e6c0-4f4d-bc70-4a14caa20466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
