<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_12345</name>
   <tag></tag>
   <elementGuidId>022891f4-ec99-45b5-b5f4-51ff23dc1442</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b201410e-3ee8-46ee-a379-ed2f23c361c0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b201410e-3ee8-46ee-a379-ed2f23c361c0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>05d7d81b-c3cc-41bf-bfd2-dda1d8eedb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>832cd727-d9b5-4bd3-ab2d-32bbef6e462b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b201410e-3ee8-46ee-a379-ed2f23c361c0</value>
      <webElementGuid>0681eb46-ced9-4f0c-8263-05d77ff4c276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>be56e873-59ca-4986-ac1c-782db5099391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>8c6f1505-c28c-4f0f-91c1-f8652a14ac8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b201410e-3ee8-46ee-a379-ed2f23c361c0&quot;)</value>
      <webElementGuid>44d69bce-1dbd-4b27-9832-61a32c5774d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b201410e-3ee8-46ee-a379-ed2f23c361c0']</value>
      <webElementGuid>0a724055-7e7f-45ed-9421-48d8ab4495b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/div/form/section/section/div[2]/div/span/span/select</value>
      <webElementGuid>84f51f4a-e0f3-44d6-97bf-32e921e50e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::select[1]</value>
      <webElementGuid>745f9e5b-363d-45a5-873e-0c3291a5558e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[2]</value>
      <webElementGuid>598a2be8-ab80-41ee-a0c4-44b2bd214f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[1]</value>
      <webElementGuid>9d332321-0365-4658-99bf-1b4e5e5091e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::select[1]</value>
      <webElementGuid>b69ea671-fc2c-4700-882e-dff94f047626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/select</value>
      <webElementGuid>008e732b-23c9-4caf-8317-9d79a58c560e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b201410e-3ee8-46ee-a379-ed2f23c361c0' and @name = 'quantity' and (text() = '12345' or . = '12345')]</value>
      <webElementGuid>b8783fc8-0e9c-4bfc-bd3e-4dca03ad54ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
