<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Remove</name>
   <tag></tag>
   <elementGuidId>83403b46-36cf-4490-8937-d5c2968060d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-button-34E.Button-button-3NM.product-productFooterRemove-2G8.Button-buttonReset-2Yb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>239ed5f9-3198-4b88-82cc-cf7c1442a18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d05344e9-1223-4e07-9458-43c778f7c669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-button-34E Button-button-3NM product-productFooterRemove-2G8 Button-buttonReset-2Yb</value>
      <webElementGuid>f49e9689-193e-480e-9ad0-71175c339b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b75f5319-4af2-4112-8175-0038e80c0d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>216fc7b0-383c-4a83-8e44-932e7a147cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container grid&quot;]/div[@class=&quot;col-span-12 col-span-8--desktop&quot;]/div[@class=&quot;cart-product-listing-root productListing-root-6sF&quot;]/ul[1]/li[@class=&quot;product-root-34V&quot;]/div[@class=&quot;product-productWrapper-El7&quot;]/div[@class=&quot;grid product-productBody-1K9&quot;]/div[@class=&quot;product-productContent-2G6 col-span-4--tablet&quot;]/span[@class=&quot;visuallyHiddenUntilTablet&quot;]/button[@class=&quot;button-button-34E Button-button-3NM product-productFooterRemove-2G8 Button-buttonReset-2Yb&quot;]</value>
      <webElementGuid>66809784-98eb-421a-9ac7-5c67336f55e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>68860c2d-717d-47e6-a322-53fafba9fc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/div/ul/li/div/div/div/span[2]/button</value>
      <webElementGuid>651efa6d-cf29-47dd-96ae-d3eed3e06b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£6.00'])[2]/following::button[1]</value>
      <webElementGuid>484dfc65-d161-4491-9ff5-d0672d0d3ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medium'])[1]/following::button[1]</value>
      <webElementGuid>bf8d1c0d-826f-469c-a8df-89112f874473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£6.00'])[3]/preceding::button[1]</value>
      <webElementGuid>cbdce909-e0a3-43c3-9acf-d386cad2d6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/preceding::button[1]</value>
      <webElementGuid>cb40f25a-50ef-4370-95aa-afc6d63a257d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>a4cdc0af-d8ab-46d5-96a8-1fbb599fd04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button</value>
      <webElementGuid>c5ac77c5-b85b-43c2-b8d2-51f44f5ed20b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Remove' or . = 'Remove')]</value>
      <webElementGuid>7a469bf2-2409-4b50-9c74-2ecd2d3671ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
