<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Quantity_product-productImage-2fw</name>
   <tag></tag>
   <elementGuidId>bbc8ebd2-3ce3-4544-abc6-e00a42af7853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[2]/div/div/ul/li[2]/div/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2a1e7479-4b44-4b60-8605-989c88458d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-productImage-2fw</value>
      <webElementGuid>62724b24-5482-425f-b092-d500ac2e7b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.secretsales.com/catalog/product/cache/54f1c1f101255c565d668037bb6945b7/5/2/5215ceb5b6fe4ba9b35ed76a58d640e4.jpg</value>
      <webElementGuid>8e5a8519-4fb7-4756-95b0-e5920eaf1dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cavalli Class Circular Wild Cat Logo Black T-Shirt</value>
      <webElementGuid>e1b1ba8b-dba6-4f9f-86b8-f4e69fbf99a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9a831fcb-7e2e-46d0-96eb-707361181c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container grid&quot;]/div[@class=&quot;col-span-12 col-span-8--desktop&quot;]/div[@class=&quot;cart-product-listing-root productListing-root-6sF&quot;]/ul[1]/li[@class=&quot;product-root-34V&quot;]/div[@class=&quot;product-productWrapper-El7&quot;]/div[@class=&quot;grid product-productBody-1K9&quot;]/a[@class=&quot;col-span-2--tablet&quot;]/img[@class=&quot;product-productImage-2fw&quot;]</value>
      <webElementGuid>849d2b3e-b2ab-4d2c-95b8-470fbbe11bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/div/ul/li[2]/div/div/a/img</value>
      <webElementGuid>3bc88975-70c3-4ff4-b302-b1644a0a549f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cavalli Class Circular Wild Cat Logo Black T-Shirt']</value>
      <webElementGuid>715410bc-aa60-4354-be0b-6702f51b1f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/a/img</value>
      <webElementGuid>c501d04d-1a3d-4cae-a6d5-1f21ffe408b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.secretsales.com/catalog/product/cache/54f1c1f101255c565d668037bb6945b7/5/2/5215ceb5b6fe4ba9b35ed76a58d640e4.jpg' and @alt = 'Cavalli Class Circular Wild Cat Logo Black T-Shirt']</value>
      <webElementGuid>628b4717-4da9-43c0-a24a-049bc5bf7ea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
