<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Quantity_icon-icon-5Yc</name>
   <tag></tag>
   <elementGuidId>155d1f13-91f2-48f6-b20d-00b00b1bf777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.product-productQuantityIcon-3bl > svg.icon-icon-5Yc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>26a93e51-b863-41ed-9cf7-5946f4c220b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>9951e507-b71b-49ed-b9a3-0ef57f2bbcdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>ae277a73-3b70-4379-900e-47939d16496f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>b4d4bffc-4ef3-4c7b-933f-f508c3647dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>0bf4c624-b4b8-4f9b-be43-718b84060bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5cbc1334-a5a7-4a48-a73b-00e354ddb0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>674cf9dd-c139-4ba3-87ce-41a55f8151d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>165beb93-0799-47ee-b156-6842ffbe944d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>fcd1d1cc-ff0c-40b0-a663-9c1e9c503925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>01729df0-c9db-44ac-825b-f169f0c58457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-icon-5Yc</value>
      <webElementGuid>99c1c36a-525c-4895-8e44-bb03ee6de980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container grid&quot;]/div[@class=&quot;col-span-12 col-span-8--desktop&quot;]/div[@class=&quot;cart-product-listing-root productListing-root-6sF&quot;]/ul[1]/li[@class=&quot;product-root-34V&quot;]/div[@class=&quot;product-productWrapper-El7&quot;]/div[@class=&quot;grid product-productBody-1K9&quot;]/span[@class=&quot;col-span-2--tablet col-span-3--desktop col-span-2--wide product-quantityWrapper-1cb visuallyHiddenUntilTablet&quot;]/form[1]/div[@class=&quot;product-productQuantityRoot-amn quantity-root-3qc&quot;]/button[@class=&quot;product-productQuantityButton-3cH quantity-button_increment-2-U quantity-button-2Hf&quot;]/span[@class=&quot;product-productQuantityIcon-3bl&quot;]/svg[@class=&quot;icon-icon-5Yc&quot;]</value>
      <webElementGuid>ad5d90eb-fc82-4a61-a369-794a8cbd743a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>19604f00-c954-4ee4-92a8-361c5e8d46d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£35.00'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>661192a7-20fb-4c38-838b-e13e8f108add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£105.00'])[3]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>70722b75-d84f-4549-ad26-6466d1844f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>13bf73dd-37dd-4190-8d8f-03ae6241cfed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
