<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Checkout</name>
   <tag></tag>
   <elementGuidId>1bffdc05-796e-4e9c-b825-206a94d7dfee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[20]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-button-34E.Button-button-3NM.miniCart-checkoutButton-3bi.button-buttonPrimary-3TM.Button-buttonPrimary-1JG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11a6d47c-abfb-4a8b-94c1-ba4b8fd0264a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1f59d05-766d-4fd2-bc00-64c66c21f576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-button-34E Button-button-3NM miniCart-checkoutButton-3bi button-buttonPrimary-3TM Button-buttonPrimary-1JG</value>
      <webElementGuid>dcb95697-b381-4a5e-9c77-2f575a01e5be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d22c4e8-f758-4dbe-b38d-eabadc7721ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Checkout</value>
      <webElementGuid>0314afd5-cc76-434e-bde3-11ece99073a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/span[@class=&quot;visuallyHiddenUntilDesktop&quot;]/aside[@class=&quot;miniCart-root-23C miniCart-root_open-3QV miniCart-root-23C miniCart-cart-2yC&quot;]/div[@class=&quot;miniCart-wrapper-3VQ&quot;]/div[@class=&quot;miniCart-footer-aDj&quot;]/button[@class=&quot;button-button-34E Button-button-3NM miniCart-checkoutButton-3bi button-buttonPrimary-3TM Button-buttonPrimary-1JG&quot;]</value>
      <webElementGuid>a12d0b0e-b2c5-4dc8-9f44-38349bc00559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>23d1c7af-b649-41e1-8ceb-832d629f202f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/span/aside/div/div[3]/button</value>
      <webElementGuid>bf506213-8b8a-4508-9f77-edfede75ea0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£35.00'])[3]/following::button[1]</value>
      <webElementGuid>c2cda64f-8940-421d-999b-7f096e45c027</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::button[1]</value>
      <webElementGuid>0fa98fc3-4c8d-4841-89e9-ebd001154010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View &amp; edit bag'])[1]/preceding::button[1]</value>
      <webElementGuid>3fdca82c-6196-44d2-ba08-4e1a56e4986d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Checkout']/parent::*</value>
      <webElementGuid>703a13a3-db6d-4e0c-9f42-280e9d123a20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div[3]/button</value>
      <webElementGuid>9aec4af3-486c-4b9e-b800-f1d6ae878a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Checkout' or . = 'Checkout')]</value>
      <webElementGuid>65fa33ef-f62a-493b-b06e-1950a50395fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
