<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_There are no items in your bag_wisepops_764f29</name>
   <tag></tag>
   <elementGuidId>410b2bdf-8283-40e6-a112-f13070bd8d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wisepops-instance-453225']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wisepops-instance-453225</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37924ede-2942-4b97-bac6-8a5cab470bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wisepops-instance-453225</value>
      <webElementGuid>1ac14d20-8729-4563-87df-88216bffde39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wisepops-instance-453225&quot;)</value>
      <webElementGuid>bfb54756-6726-47b9-89af-9d9fe8e97542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wisepops-instance-453225']</value>
      <webElementGuid>db55bb20-485b-4365-b7fb-92fa31b063eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wisepops-root']/div</value>
      <webElementGuid>5c1097ec-5391-4f55-bb6e-74b318c48ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div</value>
      <webElementGuid>39c94a66-0879-417f-973f-2653fceb4132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wisepops-instance-453225']</value>
      <webElementGuid>87208061-4cb8-4611-a47e-d05afd4c43bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
