<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , attentive_creative, , _24add5</name>
   <tag></tag>
   <elementGuidId>8270aad7-2364-42fc-9707-3c8b9c9b6169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attentive_creative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='attentive_creative']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>932a5175-0340-4efa-8cf1-0aaf24e3207c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>55d108cf-e486-4d78-814f-3890052843cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attentive_creative</value>
      <webElementGuid>0da39fe7-3915-4b5b-9965-0eff2e524579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Up via Text for Offers</value>
      <webElementGuid>218ab07f-f7be-404b-80ed-d97ff6407477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://creatives.attn.tv/creatives-dynamic/multiPage/index.html</value>
      <webElementGuid>306a25a5-7192-416e-8553-b27bc2864d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attentive_creative&quot;)</value>
      <webElementGuid>a937404d-02dc-469c-aab2-2b93bed11d08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='attentive_creative']</value>
      <webElementGuid>a02861b0-58a2-477a-8eaf-f4db31fa838b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attentive_overlay']/iframe</value>
      <webElementGuid>795a30f8-7dd7-48eb-a126-5a9cbab321c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/iframe</value>
      <webElementGuid>c6ec6544-dbda-4d4f-a796-fd10773dff0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'attentive_creative' and @title = 'Sign Up via Text for Offers' and @src = 'https://creatives.attn.tv/creatives-dynamic/multiPage/index.html']</value>
      <webElementGuid>040dd86f-22b2-4054-975a-5df215879aaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
