<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_PopupCloseButton__PopupCloseIcon-sc-srj_37a183</name>
   <tag></tag>
   <elementGuidId>82c3febb-0378-4af7-a036-21cfe6ebb79c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wisepop-453225']/button/svg</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.wisepops-style-slot > div.wisepops-render-slot > #wisepops-custom-css-453225 > #wisepops-container-453225 > #wisepop-453225 > button.PopupCloseButton__InnerPopupCloseButton-sc-srj7me-0.gjrgdL.wisepops-close > svg.PopupCloseButton__PopupCloseIcon-sc-srj7me-1.cDxkkR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e2a8d944-f3d4-46f0-b9c3-9c9f83c93cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>e3a61b26-db05-426e-90c0-650414140d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>b3d5a072-8815-46ec-9b76-7221a27f0747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 28 28</value>
      <webElementGuid>3db3bbe7-3d36-4c77-b88e-e7822b061164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>aac4eed1-a6ad-483b-bdd2-c925f4c719ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000</value>
      <webElementGuid>b8ba8573-347d-4eff-952f-f37d88315dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weight</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>faec1939-7de9-4d39-b0ca-03c1492eefb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PopupCloseButton__PopupCloseIcon-sc-srj7me-1 cDxkkR</value>
      <webElementGuid>ff33c36c-1783-43f6-b127-bda3a33c19ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/section[@class=&quot;wisepops-style-slot&quot;]/div[@class=&quot;wisepops-render-slot&quot;]/div[@id=&quot;wisepops-custom-css-453225&quot;]/div[@id=&quot;wisepops-container-453225&quot;]/div[@id=&quot;wisepop-453225&quot;]/button[@class=&quot;PopupCloseButton__InnerPopupCloseButton-sc-srj7me-0 gjrgdL wisepops-close&quot;]/svg[@class=&quot;PopupCloseButton__PopupCloseIcon-sc-srj7me-1 cDxkkR&quot;]</value>
      <webElementGuid>f315ee50-d19c-4e2e-b64a-f91875ec8581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Nike Mens Fleece Joggers in Black/div_There are no items in your bag_wisepops_764f29</value>
      <webElementGuid>06173391-2f3a-4466-9284-9c6bbd03a941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a804c49f-ca34-4a89-b7bf-24e48de9bcb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wisepop-453225']/button/svg</value>
      <webElementGuid>1f4d21f0-010a-4668-8d48-8519905a9bfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>644a8f45-5f79-4ba3-96e2-be96b03570ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
