<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Trusted by 11,000 on Trustpilot_fredhop_188312</name>
   <tag></tag>
   <elementGuidId>3d018752-68fb-4202-b54b-80fb57c9e7aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/aside/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.fredhopperFacets-shimmer-facetContainer-1oM</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a046bfd4-d96a-452f-a8da-912d72c6e716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperFacets-shimmer-facetContainer-1oM</value>
      <webElementGuid>3844ad99-4209-40fe-8b1e-1edc45cac376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4&quot;]/aside[@class=&quot;fredhopper-facets-1Oo visuallyHiddenUntilDesktop&quot;]/div[@class=&quot;Stack-stack-1rt Stack-stackSmall-1NU&quot;]/div[@class=&quot;fredhopperFacets-shimmer-facetContainer-1oM&quot;]</value>
      <webElementGuid>0598b29c-52d6-4e6b-9ba6-ea8d0bb9da35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/aside/div/div[2]</value>
      <webElementGuid>17dd237a-6c47-4ee4-88ce-1a777ffba1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trusted by 11,000+ on Trustpilot'])[1]/following::div[12]</value>
      <webElementGuid>8e41e917-8547-43e9-a28f-33d80d0754fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extended Christmas Returns until 31st January'])[1]/following::div[14]</value>
      <webElementGuid>336355f3-f58f-4124-b32e-3a6acc47d650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Join the secret'])[1]/preceding::div[395]</value>
      <webElementGuid>129cf08c-97f7-4931-b228-6f947610e9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Womenswear'])[1]/preceding::div[395]</value>
      <webElementGuid>c56c2a45-34b9-4d4f-a356-431cdbca64da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div[2]</value>
      <webElementGuid>d61f9ea3-0565-4ec3-8d1b-1d72456cf488</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
