<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_ASOS LUXE bandeau corsetted 3D floral mi_13f9d0</name>
   <tag></tag>
   <elementGuidId>adb1ecfe-1102-4ede-99e7-02fc430afebe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[2]/section[2]/div[2]/a[4]/div[2]/div/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>9df6ef88-a11e-46f4-b4de-cbc23457c6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperItem-productName-2tH</value>
      <webElementGuid>f5fc514d-0b19-4c64-96a5-de1867552ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ASOS LUXE bandeau corsetted 3D floral mini skater dress in pink</value>
      <webElementGuid>dde5b6e9-3380-4d41-8eb3-cd677ce5df61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4 fredhopper-noBreadcrumbs-3g1&quot;]/div[@class=&quot;fredhopper-content-boK&quot;]/section[2]/div[@class=&quot;fredhopper-item-list-root fredhopperItems-fredhopperItems-2di&quot;]/a[@class=&quot;fredhopper-item-root&quot;]/div[@class=&quot;Stack-stack-1rt fredhopperItem-meta-3F3 Stack-stackMedium-2TH&quot;]/div[1]/h4[@class=&quot;fredhopperItem-productName-2tH&quot;]</value>
      <webElementGuid>ced08467-04c8-4f43-9b56-5323417602c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/section[2]/div[2]/a[4]/div[2]/div/h4</value>
      <webElementGuid>206a8482-bf34-49f8-89eb-2ff5b2fd29b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Popular!'])[1]/following::h4[1]</value>
      <webElementGuid>5dbbec0a-c76c-458b-80e2-8f1d2571aceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::h4[1]</value>
      <webElementGuid>cc6e0f8f-0bba-4f25-a7f5-3aa6a5072a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£90.00'])[1]/preceding::h4[1]</value>
      <webElementGuid>d73252d9-72a9-4bfa-8b66-c4249817f8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£13.50'])[1]/preceding::h4[1]</value>
      <webElementGuid>4ee3b7b9-7585-4102-9ab5-08498ac53adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ASOS LUXE bandeau corsetted 3D floral mini skater dress in pink']/parent::*</value>
      <webElementGuid>c3dd22e2-d8f5-46f1-b161-aa1d4339ceed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div[2]/div/h4</value>
      <webElementGuid>539b7f30-b213-42ba-a627-45f7fbe6ce62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'ASOS LUXE bandeau corsetted 3D floral mini skater dress in pink' or . = 'ASOS LUXE bandeau corsetted 3D floral mini skater dress in pink')]</value>
      <webElementGuid>9bc10bf8-8503-40fb-9a63-e96c52e36562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
