<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Categories</name>
   <tag></tag>
   <elementGuidId>fc126652-5098-46e0-b518-da8f61e02594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.fredhopperFacets-button-f6L.Expandable-button-1Cy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04e6c84f-ce33-4df5-ae2d-34cf5565e3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2ab622ed-781d-4840-af5b-65407314abee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>377c1bdd-c71f-4dd2-9cc4-ecc0591dd54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e454637f-add5-426a-9a52-f07cc679e469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>0a78abff-c34d-437a-9db6-ca773a14fa50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperFacets-button-f6L Expandable-button-1Cy</value>
      <webElementGuid>9e03e9ea-7ccc-47f7-a799-d5f014e65a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>fd088958-3765-4c19-aba6-664ba55c4484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4&quot;]/aside[@class=&quot;fredhopper-facets-1Oo visuallyHiddenUntilDesktop&quot;]/div[@class=&quot;fredhopper-facetsWrapper-1JE&quot;]/div[@class=&quot;Stack-stack-1rt Stack-stackSmall-1NU&quot;]/div[@class=&quot;fredhopper-facets-root fredhopperFacets-facetsList-1Gi&quot;]/div[@class=&quot;fredhopperFacets-expandable-cUj&quot;]/button[@class=&quot;fredhopperFacets-button-f6L Expandable-button-1Cy&quot;]</value>
      <webElementGuid>7cbabc7a-d968-488f-826d-66371cb27ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>86df5630-58c1-4815-9413-3c6cf2f591c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/aside/div/div/div[2]/div/button</value>
      <webElementGuid>be4c5c91-1d30-479f-a300-5c0c1808496d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superdry'])[4]/following::button[2]</value>
      <webElementGuid>d6547f88-b00e-44f9-a9e1-705984461ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chinos'])[1]/preceding::button[1]</value>
      <webElementGuid>14c0f2b8-b7d1-499c-9048-1c9ea339954d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div[2]/div/button</value>
      <webElementGuid>6981e890-f725-472b-97b8-0efb91d40e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Categories' or . = 'Categories')]</value>
      <webElementGuid>f10357cd-a479-4f82-9ca5-b200b551dde8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Superdry'])[5]/following::button[2]</value>
      <webElementGuid>4a5b2c00-291d-4948-b133-596d9f32719e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chinos'])[2]/preceding::button[1]</value>
      <webElementGuid>b6e5174d-f436-40ac-bf65-0876cd0e7135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
