<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View  edit bag</name>
   <tag></tag>
   <elementGuidId>f9e82ecd-f9f4-419b-801e-e452f9ba64d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.button-button-34E.Button-button-3NM.miniCart-basketButton-2_J.button-buttonSkeleton-2ox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f9ad62cf-9630-423b-9f5f-7b9ecd477b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d7a835ea-3704-4158-ba7d-7751645f4bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox</value>
      <webElementGuid>f4288418-69e7-4766-aea4-9c295aa2e90e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a455ad90-a1b1-4aca-9ec1-9fee7898dfe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>desktop-view-edit-basket</value>
      <webElementGuid>1ceceb2e-09d8-4ab0-b8c4-5a3511c4cb6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View &amp; edit bag</value>
      <webElementGuid>4317bbfd-c3da-4b4c-a121-78437103377e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/span[@class=&quot;visuallyHiddenUntilDesktop&quot;]/aside[@class=&quot;miniCart-root-23C miniCart-root_open-3QV miniCart-root-23C miniCart-cart-2yC&quot;]/div[@class=&quot;miniCart-wrapper-3VQ&quot;]/div[@class=&quot;miniCart-footer-aDj&quot;]/button[@class=&quot;button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox&quot;]</value>
      <webElementGuid>761ddf96-1568-4a1c-9cea-0c5d0efb24b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>1390a150-7f4f-4434-a851-99a8586400d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/span/aside/div/div[3]/button[2]</value>
      <webElementGuid>601c57c2-dc72-4138-9aaa-727d83255ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::button[1]</value>
      <webElementGuid>8ac85c36-52f1-4d5f-8a39-69082a571a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£111.99'])[1]/following::button[2]</value>
      <webElementGuid>67f075f6-28c9-4646-b2a1-c3233346ec96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View &amp; edit bag']/parent::*</value>
      <webElementGuid>b3f411f5-7ad7-459f-a7c6-1e6ebcff31c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>45e6d070-1712-45d0-ae31-ea9d0e06f14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View &amp; edit bag' or . = 'View &amp; edit bag')]</value>
      <webElementGuid>6698472e-ccff-41b3-a7db-4b8f6baf7faf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
