<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_12345</name>
   <tag></tag>
   <elementGuidId>1106bd8b-83ce-4e9f-b18b-8059a91316f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='b50f0869-98bf-4d68-8e39-b7722a098828']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b50f0869-98bf-4d68-8e39-b7722a098828</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ffe6bbc6-0919-42a4-a1b7-a5fbcb756e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>1cb901b3-0db4-4457-9722-98ad3974654a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b50f0869-98bf-4d68-8e39-b7722a098828</value>
      <webElementGuid>031d7326-5166-45f0-b98a-a6eaacda39ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>4d8ddf31-fcc4-44c8-838f-d5c351c4bfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>449c373e-5931-437d-a6f5-d92e1e8b4151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b50f0869-98bf-4d68-8e39-b7722a098828&quot;)</value>
      <webElementGuid>8a3d49e5-43d2-4088-986a-fb0e5d254040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='b50f0869-98bf-4d68-8e39-b7722a098828']</value>
      <webElementGuid>6bb695e2-5003-4f2a-a246-13d3056734bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/div/form/section/section/div[2]/div/span/span/select</value>
      <webElementGuid>290575cf-e7b6-4bbe-8141-41d51c75c98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::select[1]</value>
      <webElementGuid>c34d47cc-43ff-45dd-9f64-1dfc0ce275fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[2]</value>
      <webElementGuid>d7892466-d2b3-4c2f-85ca-3f9fcde70afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[1]</value>
      <webElementGuid>94356d20-8a1f-4157-954b-742650dd2f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::select[1]</value>
      <webElementGuid>452c8311-9ccf-4fca-bbc9-a020b509c515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/select</value>
      <webElementGuid>1e84e4f0-6ad1-473a-aa34-0338c0e7aafe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'b50f0869-98bf-4d68-8e39-b7722a098828' and @name = 'quantity' and (text() = '12345' or . = '12345')]</value>
      <webElementGuid>196a98fd-1f01-48c4-b253-0ede89bf0c53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
