<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add To Cart</name>
   <tag></tag>
   <elementGuidId>2a5638c9-0aea-4077-aed3-0abf41d38459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_17_2_1_1699533779550_187']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sqs-add-to-cart-button-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>425ad9de-bfd4-4be7-802b-584b045031c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sqs-add-to-cart-button-inner</value>
      <webElementGuid>407d8412-8ef8-4784-b91c-f3f9598d67f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Cart</value>
      <webElementGuid>f2bd15b0-7167-4b37-af28-34e8ad8f56e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1699533779550_187&quot;)/div[@class=&quot;sqs-add-to-cart-button-inner&quot;]</value>
      <webElementGuid>228a70fd-01f2-4a91-9123-444d0b8fb790</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1699533779550_187']/div</value>
      <webElementGuid>af08a1b4-99cf-48c5-a093-17ce7b984a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::div[3]</value>
      <webElementGuid>985ab3b0-4bc5-46a3-98d1-3bd516491bfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumbo 350g in PET'])[2]/following::div[5]</value>
      <webElementGuid>3e3bd496-9360-406d-9dc9-4b0e5b228faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKIN BALM - SIGNATURE BLEND - 100 G'])[3]/preceding::div[1]</value>
      <webElementGuid>9cdbc69a-f222-4615-8721-b88ffdf357e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from £40.00'])[1]/preceding::div[3]</value>
      <webElementGuid>72207781-d111-4f3f-ac70-aadcfdf0e7fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add To Cart']/parent::*</value>
      <webElementGuid>ea8f886e-b178-41dc-a6f7-e3c4709716a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>592f0663-9f1d-40ec-826d-1341de88873b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add To Cart' or . = 'Add To Cart')]</value>
      <webElementGuid>1fc597e2-10dc-46bc-b0ef-9d14f2c84eed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
