<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View  edit bag</name>
   <tag></tag>
   <elementGuidId>52389a1a-2512-4939-9e75-009801686efb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-button-34E.Button-button-3NM.miniCart-basketButton-2_J.button-buttonSkeleton-2ox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>935a2a24-df12-44f4-903e-90760ab24f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a17d028-eb11-400f-91e2-1883c9fa957a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox</value>
      <webElementGuid>0d3e3d38-15bf-4806-8706-afc14e19f968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7658d541-60c1-4192-8165-2f5d5aefbe06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>desktop-view-edit-basket</value>
      <webElementGuid>5763ddba-3ac5-4212-a77e-3fce2524fbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View &amp; edit bag</value>
      <webElementGuid>65329502-3f99-4cad-b037-4bd43e83e8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/span[@class=&quot;visuallyHiddenUntilDesktop&quot;]/aside[@class=&quot;miniCart-root-23C miniCart-root_open-3QV miniCart-root-23C miniCart-cart-2yC&quot;]/div[@class=&quot;miniCart-wrapper-3VQ&quot;]/div[@class=&quot;miniCart-footer-aDj&quot;]/button[@class=&quot;button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox&quot;]</value>
      <webElementGuid>c5f0c7cd-b0bc-404d-a826-34777b4ff7eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[19]</value>
      <webElementGuid>6f69649b-d805-4ed1-a11f-ef5468e99be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/span/aside/div/div[3]/button[2]</value>
      <webElementGuid>cb26bbf0-7889-4ff9-b643-d21d6fb9c338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::button[1]</value>
      <webElementGuid>3063439a-1894-424f-8f9c-413677e3433c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£18.00'])[1]/following::button[2]</value>
      <webElementGuid>26fc1601-9109-4fdf-90bb-0d8657d3466c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View &amp; edit bag']/parent::*</value>
      <webElementGuid>9097f814-ff65-45ae-9b4f-61c030f99401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>a4b23ed2-98e4-49db-af38-4eca51e6c6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View &amp; edit bag' or . = 'View &amp; edit bag')]</value>
      <webElementGuid>6340c97d-6f25-4680-99d6-6216173fda87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>505e049b-a02e-423f-923f-1137d69d03f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£12.00'])[1]/following::button[2]</value>
      <webElementGuid>f68a2e22-8e66-4d00-b682-4297daec77be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
