<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View  edit bag</name>
   <tag></tag>
   <elementGuidId>07dcd67b-a869-4e57-99a6-e4c1b2c03ec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-button-34E.Button-button-3NM.miniCart-basketButton-2_J.button-buttonSkeleton-2ox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[21]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d730379d-9667-4098-8fb9-7b1b73244347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d47db1eb-63b2-4584-8d15-96f2aa1b2b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox</value>
      <webElementGuid>b1b22e20-da90-4663-97ce-cf12f0338c7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dcd3bd9e-a91f-4079-8221-aaf3d8d80a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>desktop-view-edit-basket</value>
      <webElementGuid>d8ec0c25-8349-4580-beb2-312757f2f0f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View &amp; edit bag</value>
      <webElementGuid>e0b48030-28cf-4550-af60-5a516ea7f5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/span[@class=&quot;visuallyHiddenUntilDesktop&quot;]/aside[@class=&quot;miniCart-root-23C miniCart-root_open-3QV miniCart-root-23C miniCart-cart-2yC&quot;]/div[@class=&quot;miniCart-wrapper-3VQ&quot;]/div[@class=&quot;miniCart-footer-aDj&quot;]/button[@class=&quot;button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox&quot;]</value>
      <webElementGuid>21cc4f23-77cf-49ab-8c80-99d22688447d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[21]</value>
      <webElementGuid>30918563-834e-4081-a695-f77828614572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/span/aside/div/div[3]/button[2]</value>
      <webElementGuid>5f527bc7-f487-463a-b7cf-de68e2b8e1b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::button[1]</value>
      <webElementGuid>1bedadf3-e3fe-467b-ab2e-9c09aa7a7b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£40.00'])[3]/following::button[2]</value>
      <webElementGuid>8578c473-a091-4b38-a0f8-cb60e3c30aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View &amp; edit bag']/parent::*</value>
      <webElementGuid>4d01a76a-a0f4-4700-bde7-104afb3817cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>4a772804-43db-4593-9cc3-38c2b7d1a009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View &amp; edit bag' or . = 'View &amp; edit bag')]</value>
      <webElementGuid>3c272f54-6367-4d6b-b3c9-458c029d44f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[22]</value>
      <webElementGuid>b11663bd-16a2-437e-bb41-ab2692b1617f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
