<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select a sizeUK 3UK 4UK 5UK 6_0c0ea1</name>
   <tag></tag>
   <elementGuidId>a172929a-e557-4299-bdc1-67f1dae4452a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>710f8a69-6c2b-4477-b47e-f135d309a3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>a9cf9094-a19a-4b4a-9397-e6523d017e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>16e1bde7-0369-42ac-ae78-ca285318af6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>0764b504-d4b1-4198-8338-c45eddd7dc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select a sizeUK 3UK 4UK 5UK 6UK 7UK 8UK 9UK 10UK 11</value>
      <webElementGuid>f6573bbd-48c9-4f83-a180-34fe6b401577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size&quot;)</value>
      <webElementGuid>5b5cd99e-4eff-4a75-bab3-7aca03930a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size']</value>
      <webElementGuid>d82e3f34-b3f5-498b-bfa9-22f478a2ef8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/div/form/section/section/div/div/span/span/select</value>
      <webElementGuid>acc56b3a-f8be-4f26-8333-60d419cc7835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[1]</value>
      <webElementGuid>6d2fb9ef-2a60-4926-93ff-14548084ee6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colour: Black/White'])[1]/following::select[1]</value>
      <webElementGuid>1ba6b3f6-a3f6-48ba-a0ba-e5853d9dad78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::select[1]</value>
      <webElementGuid>5ec734e0-be5c-4429-9648-cf9cc3eb6bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[2]</value>
      <webElementGuid>a0c3a043-2b1c-40ba-b809-782c0bf1af6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6f097ef2-5ce0-4f49-9536-98d1870b6af5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size' and @name = 'size' and (text() = 'Please select a sizeUK 3UK 4UK 5UK 6UK 7UK 8UK 9UK 10UK 11' or . = 'Please select a sizeUK 3UK 4UK 5UK 6UK 7UK 8UK 9UK 10UK 11')]</value>
      <webElementGuid>2f13ba55-5781-4ab4-b83d-ee3bd69799af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
