<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_12345</name>
   <tag></tag>
   <elementGuidId>fb266dc6-72ef-4fe8-bb0f-14ccdd05521a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='50f8f340-d738-4baa-83eb-268a3c00ac04']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#50f8f340-d738-4baa-83eb-268a3c00ac04</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>66e184b9-df38-4783-a839-30c4cfa25288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>8b750d18-8413-4149-8046-87014b2bd5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>50f8f340-d738-4baa-83eb-268a3c00ac04</value>
      <webElementGuid>44325172-62e6-46b7-aa04-c6ddde14a642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>f62a7188-add6-4133-bb87-23395dd62771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>7109e630-e0ee-490a-af79-fd19227ca00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;50f8f340-d738-4baa-83eb-268a3c00ac04&quot;)</value>
      <webElementGuid>7eeb15e1-255f-4461-8ff1-8fc40138fe1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='50f8f340-d738-4baa-83eb-268a3c00ac04']</value>
      <webElementGuid>7bef5bbc-75d2-4ee4-869f-69b63bf5e60a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/div/form/section/section/div[2]/div/span/span/select</value>
      <webElementGuid>c541de83-e8cc-46f4-ad25-050d33a6b0c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::select[1]</value>
      <webElementGuid>4ee40af0-c6a7-4775-a0e9-8e942b95b793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[2]</value>
      <webElementGuid>dfb16c3a-b8f0-45b1-9353-b5f7bd57071b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[1]</value>
      <webElementGuid>536b892f-d2cb-43cf-8562-313f772351c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::select[1]</value>
      <webElementGuid>134bdb9d-ace4-4be8-89ef-e1cae646b3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/select</value>
      <webElementGuid>f203e673-ee8f-4d5b-a2d0-0277e74470dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '50f8f340-d738-4baa-83eb-268a3c00ac04' and @name = 'quantity' and (text() = '12345' or . = '12345')]</value>
      <webElementGuid>9907e5cf-f6b9-4b45-8352-37ae3b5de8b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
