<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View  edit bag_wisepops-instance-453225</name>
   <tag></tag>
   <elementGuidId>5f512367-79c9-4bc2-a2a6-1996a95507c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wisepops-instance-453225']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wisepops-instance-453225</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7129e2ca-1625-4322-a156-d9b2bbd65ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wisepops-instance-453225</value>
      <webElementGuid>19c4f906-f702-4fe3-ac2a-b0b807662627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wisepops-instance-453225&quot;)</value>
      <webElementGuid>aab0f8f8-2174-41a5-ba9c-205b34314e5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wisepops-instance-453225']</value>
      <webElementGuid>f89f70a6-40ae-418d-b409-2eb65fef3a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wisepops-root']/div</value>
      <webElementGuid>9dc23811-a3f0-4f51-b162-c0e0853648ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div</value>
      <webElementGuid>1d1ee4ef-3c85-494e-84ec-15e786cff6ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wisepops-instance-453225']</value>
      <webElementGuid>336c9488-cbd0-4bd9-9095-8f04d997c47e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
