<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_PopupCloseButton__PopupCloseIcon-sc-srj7me-1 cDxkkR--453225-feb</name>
   <tag></tag>
   <elementGuidId>6e4ea8b4-2961-4c66-b11b-016429762abe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wisepop-453225']/button/svg</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>section.wisepops-style-slot > div.wisepops-render-slot > #wisepops-custom-css-453225 > #wisepops-container-453225 > #wisepop-453225 > button.PopupCloseButton__InnerPopupCloseButton-sc-srj7me-0.gjrgdL.wisepops-close > svg.PopupCloseButton__PopupCloseIcon-sc-srj7me-1.cDxkkR</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>b94963f2-3eac-4144-a4e6-2f9397d74c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>50825c61-53da-48b4-9d7b-fce211dc339e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>1dbe0fc4-1f71-4954-af46-3a10d3204fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 28 28</value>
      <webElementGuid>1600d02b-920d-4207-83c9-223160d3a720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>95f50b45-0c99-494d-b277-e381c3830688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#000</value>
      <webElementGuid>13e56e6b-ca41-4bd2-af53-b20e8f735e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>weight</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>554fedb9-6607-475e-992c-e784658df4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PopupCloseButton__PopupCloseIcon-sc-srj7me-1 cDxkkR</value>
      <webElementGuid>9b765dac-1827-4e76-997f-c8b800ccdb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/section[@class=&quot;wisepops-style-slot&quot;]/div[@class=&quot;wisepops-render-slot&quot;]/div[@id=&quot;wisepops-custom-css-453225&quot;]/div[@id=&quot;wisepops-container-453225&quot;]/div[@id=&quot;wisepop-453225&quot;]/button[@class=&quot;PopupCloseButton__InnerPopupCloseButton-sc-srj7me-0 gjrgdL wisepops-close&quot;]/svg[@class=&quot;PopupCloseButton__PopupCloseIcon-sc-srj7me-1 cDxkkR&quot;]</value>
      <webElementGuid>b9a4f409-4a56-4527-b27b-9a7f7038ad07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ASOS DESIGN wedding super skinny suit _cdc867/div_View  edit bag_wisepops-instance-453225</value>
      <webElementGuid>346803cc-f94f-4dc7-8fc8-c32ab01e1914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fe7e3a31-01e7-4eb6-8135-f6518a5b12f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wisepop-453225']/button/svg</value>
      <webElementGuid>a8c5ec7c-625b-4f0f-851f-3e0356edaac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='']/parent::*</value>
      <webElementGuid>4317fc40-ff02-4344-81fd-cdeac92b46a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
