<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Sheepskin Boots</name>
   <tag></tag>
   <elementGuidId>8e57fd8e-9fac-4be5-9eac-5937e7dca1ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fi-plp-main']/nav/ul/li[3]/a/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b73c4a4-c6c2-4427-b50c-0b437785617b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-plp-main__inner-text</value>
      <webElementGuid>dc8f70e5-6137-4840-9461-e8f476ce090b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sheepskin Boots</value>
      <webElementGuid>896aa802-6ee9-4671-bace-32a2b82103b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fi-plp-main&quot;)/nav[@class=&quot;fi-plp-main__nav&quot;]/ul[@class=&quot;fi-plp-main__list fi-list-scrollable&quot;]/li[@class=&quot;fi-plp-main__item&quot;]/a[@class=&quot;fi-link fi-plp-main__link&quot;]/div[@class=&quot;fi-plp-main__text&quot;]/span[@class=&quot;fi-plp-main__inner-text&quot;]</value>
      <webElementGuid>27d3bb90-c242-47c6-a7e7-4170b8c60f8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fi-plp-main']/nav/ul/li[3]/a/div[2]/span</value>
      <webElementGuid>367f4ba8-abdb-469a-aa84-3a319bacc13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leather Boots'])[1]/following::span[1]</value>
      <webElementGuid>552f8ea8-d50d-450a-b4ef-e61e7d604441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ankle Boots'])[1]/following::span[2]</value>
      <webElementGuid>def4ba6f-2de6-47b2-8f5c-9754bb56dc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Black Ankle Boots'])[1]/preceding::span[1]</value>
      <webElementGuid>6e8c6aae-8b4a-4047-8473-3909d7df455a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Heeled Boots'])[1]/preceding::span[2]</value>
      <webElementGuid>007bb877-9d65-4b20-81ac-1ee0982dd125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sheepskin Boots']/parent::*</value>
      <webElementGuid>09177815-3912-40fc-ab6b-3c88fa67bb91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/div[2]/span</value>
      <webElementGuid>1fae9391-88f3-4768-9bb9-171523f54806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Sheepskin Boots' or . = 'Sheepskin Boots')]</value>
      <webElementGuid>6468797c-ad57-4050-8322-ffa57ebaf705</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
