<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SHOP NOW</name>
   <tag></tag>
   <elementGuidId>767ff526-3663-4b39-bc2b-a1f745ad283f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='yui_3_17_2_1_1699533754586_626']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#yui_3_17_2_1_1699533754586_626</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9794ea3c-4040-4bc0-89ba-15cecd70eb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/shop</value>
      <webElementGuid>fdad9348-bc0f-424c-be85-160f8d079c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sqs-block-button-element--small sqs-button-element--tertiary sqs-block-button-element</value>
      <webElementGuid>8f3867dd-eac7-430d-bcde-a447bf0ce939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-initialized</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9ef7bb9c-3cfd-4e32-ab20-a143abd45e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yui_3_17_2_1_1699533754586_626</value>
      <webElementGuid>d01caf26-7508-437e-b1f7-45630f074e07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    SHOP NOW
  </value>
      <webElementGuid>74a6c6c8-509a-4826-be82-0a68029839fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1699533754586_626&quot;)</value>
      <webElementGuid>059d39b6-bcef-4171-ab18-ce031e84a99a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1699533754586_626']</value>
      <webElementGuid>2e5883a5-8edd-48a0-b4cd-c3328206f6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1699533754586_476']/a</value>
      <webElementGuid>816610b5-603b-4fd3-a377-433b662d43f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'SHOP NOW')]</value>
      <webElementGuid>adf8ecd1-126d-4bbf-a306-f583cc80c126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NURTURED BY NATURE'])[1]/following::a[1]</value>
      <webElementGuid>679cfd3d-e738-4558-970b-bcdc7a6ef42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Journal'])[3]/following::a[1]</value>
      <webElementGuid>341d0672-4954-485e-b701-8b70b5a298c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discover our plant-powered range in its most potent form.'])[1]/preceding::a[1]</value>
      <webElementGuid>54b2a630-8ba3-4351-b6d2-e5fd153816f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FACE'])[4]/preceding::a[3]</value>
      <webElementGuid>351f4960-b242-499e-8411-02b2a146cc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SHOP NOW']/parent::*</value>
      <webElementGuid>241e5d57-c77b-48ed-bc3e-0b16cc9ce974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/shop')])[28]</value>
      <webElementGuid>afb5bd3b-5c9d-44cd-a4ae-a119a6165a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/a</value>
      <webElementGuid>d9fd28ce-7c77-40e0-a7d0-675bcdb125cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/shop' and @id = 'yui_3_17_2_1_1699533754586_626' and (text() = '
    SHOP NOW
  ' or . = '
    SHOP NOW
  ')]</value>
      <webElementGuid>e590d36c-663d-43cc-9e9a-02cca73215a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
