<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>19d2a7e8-dcef-46ec-889f-f55b3af9d622</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='yui_3_17_2_1_1699533637075_626']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;EARTH FROM EARTH&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8859883a-937b-4812-ae6f-fc8b49020fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//images.squarespace-cdn.com/content/v1/6237560a2e014a631a468e0e/c1b8ffa0-87f2-4491-a157-32d125485676/logoearth.png?format=1500w</value>
      <webElementGuid>6034f8b5-6ed4-4ce8-8bc6-98ab65d2ba60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>EARTH FROM EARTH</value>
      <webElementGuid>7f1dde4f-25ba-4d8e-b392-749e643b8764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>ca704adf-435e-4c0e-833a-df96904523c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>2c08da8d-0f01-462b-adae-ba66e48ed501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>3f779d75-e521-4da8-b5b0-a91341c19266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loader</name>
      <type>Main</type>
      <value>raw</value>
      <webElementGuid>8f28ac42-5a03-44b0-829d-0f4d0f801aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1699533637075_626&quot;)/img[1]</value>
      <webElementGuid>48122365-797a-48ed-a144-d6cc50791f2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='yui_3_17_2_1_1699533637075_626']/img</value>
      <webElementGuid>1d299d02-64ba-4dbd-b236-fc11f17bac05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='EARTH FROM EARTH']</value>
      <webElementGuid>925233f4-f0dd-4662-b606-69848eeddb1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>afeb4eea-6355-488f-9fc3-82dc6d61b4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//images.squarespace-cdn.com/content/v1/6237560a2e014a631a468e0e/c1b8ffa0-87f2-4491-a157-32d125485676/logoearth.png?format=1500w' and @alt = 'EARTH FROM EARTH']</value>
      <webElementGuid>1bf4bcf4-8aff-47ca-a6a5-29602fe13f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
