<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_indicates required field_button butto_1402ef</name>
   <tag></tag>
   <elementGuidId>479f1b78-d45d-4b9c-80bc-8869c25be142</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.button.button-primary.pwa-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Sign up']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>897c95cd-6ff5-42f2-bc40-6d597bb5812f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button button-primary pwa-button</value>
      <webElementGuid>9fc80dfd-f8b5-4211-9934-e2c2254ee3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2ac78235-fef8-408d-8f20-0ff4e9caa099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Sign up</value>
      <webElementGuid>3f2e2694-8ec1-473f-9faf-1c7802b3970a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>7042b4d2-b1a2-4df5-8837-7bd44b1ad952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form7&quot;)/div[@class=&quot;o-form-button-bar&quot;]/input[@class=&quot;button button-primary pwa-button&quot;]</value>
      <webElementGuid>86800a00-7685-48fb-a0ac-d54223938de7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Sign up']</value>
      <webElementGuid>e5a635d0-9f19-41ec-ba16-9ab4d8ed9e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form7']/div[2]/input</value>
      <webElementGuid>98e42f1e-69e8-448b-8754-3ac2674e14f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>7f784452-0558-48bb-a900-028cef6704ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>686e8f0d-f8c8-4552-8313-f32c9f118f41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
