<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_lastName</name>
   <tag></tag>
   <elementGuidId>cb03d70a-fbfa-47d6-a5fe-98afdfd99006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input15']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63c429bf-21e8-4412-afec-65a1ba4795a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e046fa53-baf2-4082-ba68-562d542b02ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your last name</value>
      <webElementGuid>c6bc5165-fb72-467a-ae0f-b8db13d6892e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>55ad86a5-daae-46b6-90b1-cba8c2ef98c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input15</value>
      <webElementGuid>da8de969-5fb2-403f-b146-ad99d985e8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Last name *</value>
      <webElementGuid>b82c53ca-2393-4343-9f78-5fdec32f4bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>82b1836d-a46b-4206-afd1-a65aab82ef76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0ee283be-1476-42a7-a13a-148247b3da73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input15&quot;)</value>
      <webElementGuid>93bce792-3e77-48d0-9868-cf0725907872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input15']</value>
      <webElementGuid>16ac2c20-d20a-499b-a798-6344a81ed0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form7']/div/div[2]/div[5]/div/span/input</value>
      <webElementGuid>b6e243b7-805f-4e98-ab3c-1ab84f68f269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/span/input</value>
      <webElementGuid>2b082718-e358-4f00-aac7-7a94d9d804b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter your last name' and @name = 'lastName' and @id = 'input15']</value>
      <webElementGuid>03042e1e-f077-4985-b8fa-278d41c9677d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
