<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_username</name>
   <tag></tag>
   <elementGuidId>3ca52023-f0ee-403c-8382-d2932c6b2047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#okta-signin-username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='okta-signin-username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7ef72846-bd5e-4a31-b64a-cc364e2d0a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>099d230c-1bc2-49e8-8be2-81060db80288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email address</value>
      <webElementGuid>74074be2-cf33-4678-b13d-7a88767ec66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>1767123e-45c9-4a60-8704-6eca20a9139c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>okta-signin-username</value>
      <webElementGuid>2d25df2e-f070-4c16-806e-d891010eb408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11d1de86-9896-40cc-865b-37a6adeff96e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okta-signin-username&quot;)</value>
      <webElementGuid>5285888b-4465-484c-863b-960aa3316774</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='okta-signin-username']</value>
      <webElementGuid>2d00c26b-fb2b-4353-b7dd-b112ef95d371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form2']/div/div[2]/div/div[2]/span/input</value>
      <webElementGuid>1708fcbf-3c18-4cb7-accc-2b61c35153e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d88b54fb-d1f7-4c7f-b8e4-0022a9141d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter your email address' and @name = 'username' and @id = 'okta-signin-username']</value>
      <webElementGuid>09110e88-8ab2-45ae-a2d1-f627236cdfed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
