<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Menswear</name>
   <tag></tag>
   <elementGuidId>ffe0c742-9902-4a35-b267-d1a2b700c9da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form7']/div/div[2]/div[6]/div/label[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fe01ea3a-f0d3-44df-9611-f13fc8491ce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>registration-panel__radio-button</value>
      <webElementGuid>f63549b7-93b2-49eb-9194-048fe9663db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>male</value>
      <webElementGuid>8a3707fc-b6ff-4e90-941a-ab679ecf9d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menswear</value>
      <webElementGuid>773a9e09-4c81-43de-b7a1-1ba491a1e034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form7&quot;)/div[@class=&quot;o-form-content o-form-theme clearfix&quot;]/div[@class=&quot;o-form-fieldset-container&quot;]/div[@class=&quot;o-form-fieldset o-form-label-top&quot;]/div[@class=&quot;o-form-input&quot;]/label[@class=&quot;registration-panel__radio-button&quot;]</value>
      <webElementGuid>171b4a02-042f-400f-9170-ba9afa8b80e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form7']/div/div[2]/div[6]/div/label[2]</value>
      <webElementGuid>cae89206-a029-4716-bb9c-941c5d8b3b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Womenswear'])[1]/following::label[1]</value>
      <webElementGuid>e53a1f18-f0bf-4465-9682-a03cdbcbf57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name*'])[1]/following::label[2]</value>
      <webElementGuid>ecbdd862-b4a8-46d1-b326-1feea5f5e7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allow brands I purchase to email me future information on offers and new launches'])[1]/preceding::label[1]</value>
      <webElementGuid>8ab81de9-4541-4e08-84f2-4de6362a3cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='* indicates required field'])[1]/preceding::label[2]</value>
      <webElementGuid>50d581a1-f3f9-403c-bd9c-9fe94407f84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menswear']/parent::*</value>
      <webElementGuid>756a60b8-f923-4a88-9344-5a9e50fb8855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label[2]</value>
      <webElementGuid>b9ece5e1-bde6-4452-b99c-8a03b69579a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Menswear' or . = 'Menswear')]</value>
      <webElementGuid>f338adbc-a65b-4440-b81c-7f1f2d583472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
