<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>legend_Email Address</name>
   <tag></tag>
   <elementGuidId>5981548e-4151-4e9a-9fd9-74a18f49fac0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form7']/div/div[2]/div/div/legend</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>legend.registration-panel__legend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>legend</value>
      <webElementGuid>1a788219-5fdd-48cd-be78-51bc8b373977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>registration-panel__legend</value>
      <webElementGuid>1e55bb5f-9948-4220-81a3-e6286810b92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Email Address *</value>
      <webElementGuid>e6ebbee4-a194-48d4-9d52-f88a3702fea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form7&quot;)/div[@class=&quot;o-form-content o-form-theme clearfix&quot;]/div[@class=&quot;o-form-fieldset-container&quot;]/div[@class=&quot;o-form-fieldset o-form-label-top&quot;]/div[@class=&quot;o-form-input&quot;]/legend[@class=&quot;registration-panel__legend&quot;]</value>
      <webElementGuid>f2032098-e2ba-4ff0-bb59-078e6e093069</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form7']/div/div[2]/div/div/legend</value>
      <webElementGuid>453bdb30-d9e7-4bf3-a353-93a1d1ad2cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Sign up below, it', &quot;'&quot;, 's quick and easy.')])[1]/following::legend[1]</value>
      <webElementGuid>698b636b-8f79-4b28-a5c9-53799ed44420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::legend[1]</value>
      <webElementGuid>bb84dd8e-ad41-4924-9c80-7eee1eeabb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password *'])[1]/preceding::legend[1]</value>
      <webElementGuid>f5ac614e-4ed5-40be-88bd-7e609e393046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Please email me SecretSales', &quot;'&quot;, ' latest offers and discounts')])[1]/preceding::legend[2]</value>
      <webElementGuid>627f6476-e3be-4c1f-a409-bd79877c2bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Email Address *']/parent::*</value>
      <webElementGuid>d5c8736a-c7c4-45ab-85c7-22c5587c5a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//legend</value>
      <webElementGuid>abe481ff-9aa9-4322-a8b7-5c4fa0853299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//legend[(text() = 'Email Address *' or . = 'Email Address *')]</value>
      <webElementGuid>4a549405-9b36-4910-8ad4-f4bfbe34aa19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
