<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_exclusive_injected-svg</name>
   <tag></tag>
   <elementGuidId>7f643e03-cf50-4163-a563-994c48d891b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='exclusive'])[1]/preceding::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.injected-svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>43c31231-e64c-49d0-8c73-43947bb41f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>0d1f72cf-9e11-4930-b893-cb40003c3544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>2dfc2bc0-b1d9-464f-a22b-fe6609dee989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6fae6499-aa85-4e30-a26b-131fc33915e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 410 410</value>
      <webElementGuid>0b8dc205-acf6-4932-8c5c-c64f6c1faf61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>276e48c3-149b-4db7-820f-eb94a67e4b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>injected-svg</value>
      <webElementGuid>06c7d256-fdc7-4114-8de8-a62679fce138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>/dialogClose-akR.svg</value>
      <webElementGuid>604e1e05-1e12-47c3-b07b-e242473292ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns:xlink</name>
      <type>Main</type>
      <value>http://www.w3.org/1999/xlink</value>
      <webElementGuid>6e56a7e4-f23f-4356-841e-bb79b887e9a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/aside[@class=&quot;adidas-modal-root dialog-root_open-1YZ&quot;]/div[@class=&quot;dialog-form-2_p&quot;]/div[@class=&quot;gatedAccessModal-dialog-1ub&quot;]/div[@class=&quot;gatedAccessModal-header-1ZZ&quot;]/button[@class=&quot;dialog-headerButton-3lY&quot;]/div[1]/div[1]/svg[@class=&quot;injected-svg&quot;]</value>
      <webElementGuid>05d6a1a1-419d-4db6-9f36-c12c6b56bb6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='exclusive'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>66e529c7-1b8b-4358-92b4-fd3d47c3dafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='up to 50% off'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>23bcaf1e-89b5-4e9d-81f3-f11f147b9df3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
