<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Outlet</name>
   <tag></tag>
   <elementGuidId>64ac2c7b-edda-4486-b1f5-905a09cce4c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[3]/div/div/nav/div/div/div/div/div/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.c-navigation__categories > li:nth-of-type(9) > a.c-ev-attached</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1dc41647-76b5-4452-8878-c99b0468c49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.secretsales.com/browse/products/shop-by/discount_percentage_gb/0.69%3Cdiscount_percentage_gb%3C1.0/</value>
      <webElementGuid>2e6e2062-2267-4ce3-aa0b-fe2a191d509e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-ev-attached</value>
      <webElementGuid>c83c8794-a4a1-4120-8fb2-41846956fb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outlet</value>
      <webElementGuid>8029f888-7ce6-42e0-951d-86569881f80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/header[@class=&quot;header-root header-root-2P7&quot;]/div[@class=&quot;container header-content-BBd&quot;]/div[@class=&quot;header-actionsWrapper-1gF&quot;]/div[@class=&quot;header-store-nav header-primaryActions-2bB&quot;]/nav[@class=&quot;visuallyHiddenUntilDesktop&quot;]/div[@class=&quot;header-desktopNavWrapper-S9Y&quot;]/div[@class=&quot;c-navigation__categories&quot;]/div[@class=&quot;cmsBlock-content-_Ac&quot;]/div[1]/div[@class=&quot;html-root-2b-&quot;]/ul[@class=&quot;c-navigation__categories&quot;]/li[9]/a[@class=&quot;c-ev-attached&quot;]</value>
      <webElementGuid>b9b1278e-a27b-46d6-a5e3-87232f1a2de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[3]/div/div/nav/div/div/div/div/div/ul/li[9]/a</value>
      <webElementGuid>0c55f5ba-0c31-472a-a500-f360b48ead95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Outlet')])[4]</value>
      <webElementGuid>27aa9606-d4cc-4d8b-af89-8d6e82d16240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Gift Guide'])[1]/following::a[1]</value>
      <webElementGuid>36fe8e84-29df-4127-baa7-7ffb48ed7f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stocking Fillers under £10'])[1]/following::a[2]</value>
      <webElementGuid>babb0efe-d62b-4644-99c1-9c8e2b76c720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[3]/preceding::a[1]</value>
      <webElementGuid>81abb77b-e5dc-4d65-bbb7-ff84d1482059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop All'])[19]/preceding::a[1]</value>
      <webElementGuid>dc547b52-21c8-4771-bad1-8ab74a036a1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outlet']/parent::*</value>
      <webElementGuid>8864b937-820b-4f41-b6ce-3bbae0cce195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.secretsales.com/browse/products/shop-by/discount_percentage_gb/0.69%3Cdiscount_percentage_gb%3C1.0/')]</value>
      <webElementGuid>c7d6f1ce-2f73-4e83-a17d-292ef2cea2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>70c59582-8145-451e-b345-0519cfe5ecb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.secretsales.com/browse/products/shop-by/discount_percentage_gb/0.69%3Cdiscount_percentage_gb%3C1.0/' and (text() = 'Outlet' or . = 'Outlet')]</value>
      <webElementGuid>b77e816c-a563-4b01-9433-8e50f199259b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
