<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dont go yet Sign-up for 10 OFF  beat th_2fc90b</name>
   <tag></tag>
   <elementGuidId>f5a130b3-4cea-4b36-b9e5-4110a260107e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overlayContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#overlayContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e5204fa-b72d-4d2d-a565-9aa1558daa8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>overlayContainer</value>
      <webElementGuid>2c831c0e-c6ee-4df3-9a99-d4e6ae409254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-woxaoh</value>
      <webElementGuid>05ae57e8-de0c-4c89-8646-43c59a3e6547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Don't go yet! Sign-up for 10% OFF + beat the Black Friday rush✓ Unmissable Black Friday deals✓ Exclusive VIP promotions &amp; new brand launches✓ FREE &amp; FAST DELIVERY WomensMensBothEmail AddressSIGN UP NOW *By signing up to emails from Secret Sales, you agree to the following Privacy Policy. Offer applies to new subscribers with an order of £50 minimum.</value>
      <webElementGuid>962bf5e9-9dd3-463b-8226-6fca2db2c453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overlayContainer&quot;)</value>
      <webElementGuid>1638a8fc-be37-4380-9965-a994cc0b6f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SECRET SALES  BLACK FRIDAY PREVIEW  UP_33cc2b/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>8c396761-fc0c-4a64-b349-3604a4620e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='overlayContainer']</value>
      <webElementGuid>8c51c309-d8c6-4f81-b796-b003f22aec1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialogContainer']/main/div</value>
      <webElementGuid>d0e61af8-77bd-4bc3-9061-36cc1f712529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div</value>
      <webElementGuid>a6945349-cbd4-4bb3-a084-8497f0b72569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'overlayContainer' and (text() = concat(&quot;Don&quot; , &quot;'&quot; , &quot;t go yet! Sign-up for 10% OFF + beat the Black Friday rush✓ Unmissable Black Friday deals✓ Exclusive VIP promotions &amp; new brand launches✓ FREE &amp; FAST DELIVERY WomensMensBothEmail AddressSIGN UP NOW *By signing up to emails from Secret Sales, you agree to the following Privacy Policy. Offer applies to new subscribers with an order of £50 minimum.&quot;) or . = concat(&quot;Don&quot; , &quot;'&quot; , &quot;t go yet! Sign-up for 10% OFF + beat the Black Friday rush✓ Unmissable Black Friday deals✓ Exclusive VIP promotions &amp; new brand launches✓ FREE &amp; FAST DELIVERY WomensMensBothEmail AddressSIGN UP NOW *By signing up to emails from Secret Sales, you agree to the following Privacy Policy. Offer applies to new subscribers with an order of £50 minimum.&quot;))]</value>
      <webElementGuid>ab5b7f03-0800-484a-adea-b6c798ed3609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
