<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , attentive_creative, , _24add5</name>
   <tag></tag>
   <elementGuidId>5eadfbaa-e301-433c-83a9-b030034d782a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='attentive_creative']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attentive_creative</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>835831c0-d9ee-4890-9dd5-313ac821b9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>9be42769-b8f2-4953-b8d3-3e9547e71baf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attentive_creative</value>
      <webElementGuid>debade2d-4c97-48ad-a90c-b9e40969957b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Up via Text for Offers</value>
      <webElementGuid>0212afb6-27ba-4aaf-adf5-d2f2420f5e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://creatives.attn.tv/creatives-dynamic/multiPage/index.html</value>
      <webElementGuid>dba2af00-8235-4e25-9692-2eb0dc3eb195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attentive_creative&quot;)</value>
      <webElementGuid>46c8baf0-6f8f-4dc9-9f60-1cc735ffea66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='attentive_creative']</value>
      <webElementGuid>b82426e4-c60b-4db0-9760-2c558a7c8748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attentive_overlay']/iframe</value>
      <webElementGuid>a258ef46-caf2-41b1-9cad-47be3a263938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/iframe</value>
      <webElementGuid>d73d95d7-4b1b-4db3-af37-6d927d66fff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'attentive_creative' and @title = 'Sign Up via Text for Offers' and @src = 'https://creatives.attn.tv/creatives-dynamic/multiPage/index.html']</value>
      <webElementGuid>2aa19d91-5c52-47fd-ad24-a5c46fbfd306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
