<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_45.00</name>
   <tag></tag>
   <elementGuidId>317dcfbe-0f6a-4340-b317-68527af0ad4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[2]/section[2]/div[2]/a/div[2]/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fredhopperItemPrices-fredhopperItemPricesCurrentPrice-28v</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>383b7380-930c-40cc-89f1-6e250ab7b273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperItemPrices-fredhopperItemPricesCurrentPrice-28v</value>
      <webElementGuid>52d7bfc5-766a-414a-bcf9-730aa6c93e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£45.00</value>
      <webElementGuid>58ba8b6a-9c6c-498e-abda-90f7a85ecd53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4 fredhopper-noBreadcrumbs-3g1&quot;]/div[@class=&quot;fredhopper-content-boK&quot;]/section[2]/div[@class=&quot;fredhopper-item-list-root fredhopperItems-fredhopperItems-2di&quot;]/a[@class=&quot;fredhopper-item-root&quot;]/div[@class=&quot;Stack-stack-1rt fredhopperItem-meta-3F3 Stack-stackMedium-2TH&quot;]/div[@class=&quot;Inline-inline-1-W fredhopperItemPrices-fredhopperItemPrices-1oK Inline-alignItemsCenter-3Z5&quot;]/span[@class=&quot;fredhopperItemPrices-fredhopperItemPricesCurrentPrice-28v&quot;]</value>
      <webElementGuid>21e303c4-96e8-45c9-985e-a65d64f1c30f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/section[2]/div[2]/a/div[2]/div[2]/span[2]</value>
      <webElementGuid>d9118140-44ba-4bc2-9ccf-e9e5034fded3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£79.99'])[1]/following::span[1]</value>
      <webElementGuid>d4cba6ea-e037-4f7d-8368-60184d49a746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Men', &quot;'&quot;, 's Lacoste Drawsting Logo Branded Jogger in Black')])[1]/following::span[2]</value>
      <webElementGuid>f4941431-28bb-4219-bcf1-9add87394a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::span[2]</value>
      <webElementGuid>4588b0db-aaf8-40cf-9827-e82a2d793655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='£45.00']/parent::*</value>
      <webElementGuid>59adccae-a0fe-40f7-a899-3e4ebb22ebcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span[2]</value>
      <webElementGuid>cd73afd4-61f3-4235-a8f9-7e7d8a49c9b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '£45.00' or . = '£45.00')]</value>
      <webElementGuid>56d244b2-9f0e-41d3-b3fa-0c6379a0a39d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
