<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Categories (1)</name>
   <tag></tag>
   <elementGuidId>8a0006fa-0698-4455-8e82-fe6f841b99f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.fredhopperFacets-button-f6L.Expandable-button-1Cy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bb479511-7734-45c2-ba8d-256fd3ec558f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b3f3863-fe49-4de1-b371-5b9ab3ca4bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>ff58feb2-82c2-453a-84ee-533858f3ac52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82dad29a-176a-495c-bce5-8f0f1e8298c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>d962d8b8-5f96-460c-97d2-522069c30aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperFacets-button-f6L Expandable-button-1Cy</value>
      <webElementGuid>93e35aa4-c2d9-4f23-87ab-21c48049a04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Categories</value>
      <webElementGuid>04f572da-04be-429a-bf4e-26a16c2ed5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4 fredhopper-noBreadcrumbs-3g1&quot;]/aside[@class=&quot;fredhopper-facets-1Oo visuallyHiddenUntilDesktop&quot;]/div[@class=&quot;fredhopper-facetsWrapper-1JE&quot;]/div[@class=&quot;Stack-stack-1rt Stack-stackSmall-1NU&quot;]/div[@class=&quot;fredhopper-facets-root fredhopperFacets-facetsList-1Gi&quot;]/div[@class=&quot;fredhopperFacets-expandable-cUj&quot;]/button[@class=&quot;fredhopperFacets-button-f6L Expandable-button-1Cy&quot;]</value>
      <webElementGuid>bf7c4f88-6882-47e5-97f6-7b691c458286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>0f88e96b-c75d-4864-9301-b5bf36523138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/aside/div/div/div[2]/div/button</value>
      <webElementGuid>c0a619ed-6115-4b19-8110-4986e50e5fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::button[2]</value>
      <webElementGuid>701a2671-824b-4efa-8d61-80197857fac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accessories'])[11]/preceding::button[1]</value>
      <webElementGuid>6aa3f0f9-c2cc-4255-8e57-cd8677beb44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/div/div/div[2]/div/button</value>
      <webElementGuid>c9e87a02-2bd3-4767-a508-d7f7ca95a430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Categories' or . = 'Categories')]</value>
      <webElementGuid>8979958f-9ce0-4a00-af0b-5bc159f1dd76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
