<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_View  edit bag</name>
   <tag></tag>
   <elementGuidId>99ab52c8-7ddc-4843-9fb0-babca1be5b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button-button-34E.Button-button-3NM.miniCart-basketButton-2_J.button-buttonSkeleton-2ox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[17]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>745491a0-9472-4c18-ab5c-67ab84b81b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>faa51693-ae75-4f73-8dad-85104d93fa5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox</value>
      <webElementGuid>01b3d28e-e310-4331-9cf9-7ab14aaadb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>df3f4b8b-aef5-4c52-ad67-938de9825201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>desktop-view-edit-basket</value>
      <webElementGuid>b72b1abf-33e5-4291-8f46-2ab652626d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View &amp; edit bag</value>
      <webElementGuid>dcb4fa32-d040-460e-b9d4-251fc54d07ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/span[@class=&quot;visuallyHiddenUntilDesktop&quot;]/aside[@class=&quot;miniCart-root-23C miniCart-root_open-3QV miniCart-root-23C miniCart-cart-2yC&quot;]/div[@class=&quot;miniCart-wrapper-3VQ&quot;]/div[@class=&quot;miniCart-footer-aDj&quot;]/button[@class=&quot;button-button-34E Button-button-3NM miniCart-basketButton-2_J button-buttonSkeleton-2ox&quot;]</value>
      <webElementGuid>66dc8a66-cf2a-4140-b994-256c58850f27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[17]</value>
      <webElementGuid>6cfe7448-cb10-4a13-8053-5c49520bef6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/span/aside/div/div[3]/button[2]</value>
      <webElementGuid>13aaaa6c-a4e2-40d4-8197-27ca22ee9a64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::button[1]</value>
      <webElementGuid>214915d7-5911-481b-aeb8-84e349d72428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£97.89'])[1]/following::button[2]</value>
      <webElementGuid>d78bf87c-b70a-4873-a319-5718ce51fa4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View &amp; edit bag']/parent::*</value>
      <webElementGuid>1e79deac-d982-4879-aeb9-bcc149e21994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button[2]</value>
      <webElementGuid>a8f0408c-f904-48de-a430-c05c27515a03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'View &amp; edit bag' or . = 'View &amp; edit bag')]</value>
      <webElementGuid>0c86d65d-9a34-466b-9f7c-efedfa55792f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[20]</value>
      <webElementGuid>b9f4ee5f-f847-41ac-b954-eb9818107a01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£29.70'])[1]/following::button[2]</value>
      <webElementGuid>0ee50770-0555-4ad4-9cd7-a28abcc5f52c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
