<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_GANT</name>
   <tag></tag>
   <elementGuidId>734de500-af4c-49ea-8033-cdd4abbf5ea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.html-root-2b-.uxtracking-FEATUREBOX3_aquascutum > a > #hero</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//h2[@id='hero'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>4b5f1196-5366-4012-a435-fe54a0b82203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hero</value>
      <webElementGuid>e6a140e9-59ea-400f-80fa-179b78ac5631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GANT</value>
      <webElementGuid>3207369b-005d-466e-9de3-259739258789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;cms-root&quot;]/div[@class=&quot;row-contained-9Ys row-root-3E7&quot;]/div[1]/div[@class=&quot;columnGroup-root-1tm&quot;]/div[@class=&quot;column-root-2pW pagebuilder-column bannerleft&quot;]/div[@class=&quot;html-root-2b- uxtracking-FEATUREBOX3_aquascutum&quot;]/a[1]/h2[@id=&quot;hero&quot;]</value>
      <webElementGuid>1a5ac159-9058-4141-b013-f12422a795da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//h2[@id='hero'])[3]</value>
      <webElementGuid>ab3a9978-c057-41bd-b189-b55d3473ecfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[3]/div/div/div/div[3]/div/a/h2</value>
      <webElementGuid>e7c694b5-ec29-44fc-844e-8e30a0daf93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIESEL'])[1]/following::h2[1]</value>
      <webElementGuid>49de2d1a-7b95-43e9-ada4-46c6a0eeae83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TED BAKER OUTLET'])[1]/following::h2[2]</value>
      <webElementGuid>b24038ce-34f7-4b4d-bbbf-609e8807941d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUMA'])[5]/preceding::h2[1]</value>
      <webElementGuid>56b3e65c-3bcd-4bad-8aba-1cae9bb7158b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRAINERS'])[1]/preceding::h2[2]</value>
      <webElementGuid>b3ad7855-503a-404b-b993-c17da96aa194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GANT']/parent::*</value>
      <webElementGuid>2f9e38b9-fa91-4e01-a19a-a7ff471af758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/h2</value>
      <webElementGuid>520e8a18-08ff-4bac-9d5c-5b6aedd8182e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'hero' and (text() = 'GANT' or . = 'GANT')]</value>
      <webElementGuid>a6c4d0ec-a31e-44e5-9362-38d833967f5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PUMA'])[4]/preceding::h2[1]</value>
      <webElementGuid>48749e1b-b973-4ccd-ae1b-75e7d6c95a2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
