<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Trusted by 11,000 on Trustpilot_image-img-L2s</name>
   <tag></tag>
   <elementGuidId>22516b2d-4ab1-44b8-9ccf-4894f6dcfb7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.column-root-2pW.pagebuilder-column > figure > a > picture > img.image-img-L2s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[2]/div/div/div/div[2]/figure/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b33534ef-caad-4dd2-b54b-c70cd39064c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-img-L2s</value>
      <webElementGuid>6208d959-1202-4be8-b51d-e412ffba5a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.secretsales.com/cdn-cgi/image/quality=85,format=auto/https://media.secretsales.com/wysiwyg/Contact_Us_2.png</value>
      <webElementGuid>d2d22140-42da-4338-8b41-f51ddb444524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Contact us</value>
      <webElementGuid>8c00a5ba-3303-48a2-bad0-cbdffd62ceaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2f535705-a682-4064-b6f7-cea88106f425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;cms-root&quot;]/div[@class=&quot;row-contained-9Ys row-root-3E7&quot;]/div[1]/div[@class=&quot;columnGroup-root-1tm&quot;]/div[@class=&quot;column-root-2pW pagebuilder-column&quot;]/figure[1]/a[1]/picture[1]/img[@class=&quot;image-img-L2s&quot;]</value>
      <webElementGuid>88685779-a7fe-45cf-b31d-4516555a04cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/div/div/div[2]/figure/a/picture/img</value>
      <webElementGuid>8b8941b3-7213-455f-bdcc-b4cb6bebcacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Contact us']</value>
      <webElementGuid>9ffb7b3d-a034-4ff1-8930-72bc4fa638c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/figure/a/picture/img</value>
      <webElementGuid>67d8a803-bbb2-422b-b3ba-8977a0016243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.secretsales.com/cdn-cgi/image/quality=85,format=auto/https://media.secretsales.com/wysiwyg/Contact_Us_2.png' and @alt = 'Contact us']</value>
      <webElementGuid>f0db6505-5800-4f4b-8c8d-fa6d3fda90ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
