<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search_productSearchDesktop</name>
   <tag></tag>
   <elementGuidId>06f129e9-6b2e-4405-96c3-2f6b075f8640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productSearchDesktop</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='productSearchDesktop']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8854639e-9e0b-4f8e-8959-7d96d76e7572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>222c0e05-2a42-4a99-8675-3e52f7103467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchSuggest-input-2f8 TextInput-textInput-3MB</value>
      <webElementGuid>7dec6166-b757-4961-9cc9-e2ecef7990ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productSearchDesktop</value>
      <webElementGuid>69cacd33-4495-4d6a-88e6-81cd8e053507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productSearchDesktop&quot;)</value>
      <webElementGuid>2d95cc52-2c7d-4891-80b3-75ddcc037ebd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='productSearchDesktop']</value>
      <webElementGuid>75234122-f234-473c-aaa7-8a69670aef09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[3]/div/div[2]/div[2]/div/div/form/div/input</value>
      <webElementGuid>d434e7ba-9846-46a7-920b-c22f35d01fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f7ad12cf-11fc-4444-83ba-c774b5528259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'productSearchDesktop']</value>
      <webElementGuid>2c559cb7-8c53-494a-b57e-139644a66c65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
