<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>line</name>
   <tag></tag>
   <elementGuidId>9b435e9c-7afb-4ef5-8fbb-03f3db5d4111</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;closeIconSvg&quot;)/line[1][count(. | //line[@x1 = '5' and @x2 = '40' and @y1 = '5' and @y2 = '40' and @ref_element = 'Object Repository/iframe_concat(id(, , attentive_creative, , _24add5' and @ref_element_is_shadow_root = 'true']) = count(//line[@x1 = '5' and @x2 = '40' and @y1 = '5' and @y2 = '40' and @ref_element = 'Object Repository/iframe_concat(id(, , attentive_creative, , _24add5' and @ref_element_is_shadow_root = 'true'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>line</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>line</value>
      <webElementGuid>77e3bd8d-89a2-4237-82c9-6306eae7bc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x1</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>63893084-63c8-49a0-91f8-2052027c5b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x2</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>defae27e-c389-42af-982d-bb464fee71a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y1</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1b368b49-626b-409c-8114-3e1c421437f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y2</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d0977625-5c46-4c62-8153-91221f15d1bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeIconSvg&quot;)/line[1]</value>
      <webElementGuid>081a2e3c-7d62-434f-a07b-abe0b958f428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>792a9590-0ac9-49c4-88a9-9475bb21d687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e599bc9f-3f90-4153-a4b4-d8c933343c4a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
