<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>section_Adding</name>
   <tag></tag>
   <elementGuidId>7d919e98-308f-4bcf-b4c0-f5f25618527b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form > section:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[2]/div/form/section[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>section</value>
      <webElementGuid>ff2de269-7b9a-48b4-b64a-de6ba21b742f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Adding</value>
      <webElementGuid>2ead82b3-020c-46d3-a9a2-17adfe9edc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;product-full-detail-root container&quot;]/div[@class=&quot;grid productFullDetail-root-1o4&quot;]/div[@class=&quot;product-details-root col-span-12 col-span-5--tablet col-span-4--desktop&quot;]/form[1]/section[2]</value>
      <webElementGuid>0a9c9869-b281-489d-875a-989b459a895f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/div/form/section[2]</value>
      <webElementGuid>3cb629a0-a6ef-4af1-896c-d8d8a8d18f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::section[1]</value>
      <webElementGuid>ad8a5ee5-080d-4c1a-9191-9284cca98f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::section[1]</value>
      <webElementGuid>f8d05ec1-e75f-4092-ae0b-aee2a02fc4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::section[1]</value>
      <webElementGuid>4fab6329-66ee-48b7-9e84-be38f2ac849f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/section[2]</value>
      <webElementGuid>537d0332-41b6-4ccc-a99e-abfa34d7bafd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//section[(text() = 'Adding' or . = 'Adding')]</value>
      <webElementGuid>6a6c5e10-a56c-4b74-b16b-e4e90dc31c1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
