<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_-37</name>
   <tag></tag>
   <elementGuidId>a54c3931-3343-4999-84cb-fdb22735cad9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[3]/section[2]/div[2]/a[2]/div[2]/div[2]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6e99fccf-0e36-49ec-9b84-9b09ee050f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperItemPrices-fredhopperItemPricesPriceDifference-38t</value>
      <webElementGuid>3d66f8ad-370f-4a27-be57-0c51cd75f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>-37%</value>
      <webElementGuid>6e75efb7-bc41-4340-8f12-98d0511d876f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4&quot;]/div[@class=&quot;fredhopper-content-boK&quot;]/section[2]/div[@class=&quot;fredhopper-item-list-root fredhopperItems-fredhopperItems-2di&quot;]/a[@class=&quot;fredhopper-item-root&quot;]/div[@class=&quot;Stack-stack-1rt fredhopperItem-meta-3F3 Stack-stackMedium-2TH&quot;]/div[@class=&quot;Inline-inline-1-W fredhopperItemPrices-fredhopperItemPrices-1oK Inline-alignItemsCenter-3Z5&quot;]/span[@class=&quot;fredhopperItemPrices-fredhopperItemPricesPriceDifference-38t&quot;]</value>
      <webElementGuid>b4fe834d-20f1-4299-913a-a19fd615ce4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/section[2]/div[2]/a[2]/div[2]/div[2]/span[3]</value>
      <webElementGuid>0a1b8f16-55f0-4b74-887c-b7fe8cc82ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£14.49'])[1]/following::span[1]</value>
      <webElementGuid>4f893ca8-2fa7-4624-8259-d251b59a4c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£22.99'])[1]/following::span[2]</value>
      <webElementGuid>c9d26e40-8cee-4162-b2b6-d1aaffdd15ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kruze | Womens Stretch Leggings - Black'])[1]/preceding::span[1]</value>
      <webElementGuid>558cfdf4-2522-4b2c-b330-16e9828de74b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£24.99'])[1]/preceding::span[1]</value>
      <webElementGuid>0edc8e38-278e-4a55-b1e4-3a5935022817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/div[2]/div[2]/span[3]</value>
      <webElementGuid>814f9bce-7ab4-4596-9692-0ebdacc4fa6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '-37%' or . = '-37%')]</value>
      <webElementGuid>771794ec-91a0-43b5-b67f-cf08728bb666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
