<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_concat(Don, , t go yet Sign-up for 1_e5f9eb</name>
   <tag></tag>
   <elementGuidId>f9af2fe5-6c44-4c5d-8bdb-8ea9588a4111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeIconContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeIconContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f7555ce-f6b2-412e-a288-5adff8ddfa11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeIconContainer</value>
      <webElementGuid>bee4455d-f875-4aeb-b075-ddfcbc56f287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>closeIcon</value>
      <webElementGuid>7d327621-98c3-41f8-875d-9d0294797830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dismiss this popup</value>
      <webElementGuid>f898d0c4-37e6-4466-b3c4-3551f4a5f902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attn-element-id</name>
      <type>Main</type>
      <value>9JPo</value>
      <webElementGuid>921f89e8-4677-48f2-8ce4-bcc8df65b6b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1glrhkl</value>
      <webElementGuid>4af0b43f-ad4b-4d19-a936-7878604bd7b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeIconContainer&quot;)</value>
      <webElementGuid>b6db61e8-6f81-401a-80c8-6584349e92fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Search results for t shirts/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>ccb0f921-7a33-401e-a6ab-d8dbc2d918de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeIconContainer']</value>
      <webElementGuid>e12f2b64-10a8-4a6b-97bb-33250e81f5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/button</value>
      <webElementGuid>eb7d6e85-a889-456d-b58d-2e956bec3ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't go yet! Sign-up for 10% OFF + beat the Black Friday rush')])[1]/preceding::button[1]</value>
      <webElementGuid>f47dfb09-c47b-4e6c-bdc0-15e7941c4397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ Unmissable Black Friday deals'])[1]/preceding::button[1]</value>
      <webElementGuid>7def4fcb-e581-4a7f-a03e-7beac3775709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b9ade457-adde-45b2-9023-09901b2bf780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeIconContainer']</value>
      <webElementGuid>e73bb28e-bdce-4f14-a3b9-c0bbad604dc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
