<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , attentive_creative, , _24add5</name>
   <tag></tag>
   <elementGuidId>7b5fabd7-832c-4a39-880b-83220b2ef47b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attentive_creative</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='attentive_creative']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>81d50a32-d4b0-4ece-a967-d85078649092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>fd2a3d3f-82b5-493d-b5ff-4fbdb4e88243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attentive_creative</value>
      <webElementGuid>c2dc3f0e-4d07-452f-9f3d-71ed1d06d8be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Up via Text for Offers</value>
      <webElementGuid>97586500-f00d-4c60-9327-f3a07a59bb11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://creatives.attn.tv/creatives-dynamic/multiPage/index.html</value>
      <webElementGuid>796a5baa-45fe-456b-9d3b-4465e345a00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attentive_creative&quot;)</value>
      <webElementGuid>0b94aaaf-4e10-4c61-8b35-262f14547867</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='attentive_creative']</value>
      <webElementGuid>24254a2d-121c-4afe-b764-07184ef403ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attentive_overlay']/iframe</value>
      <webElementGuid>76df1632-53f0-4582-bb65-e5d05998669a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/iframe</value>
      <webElementGuid>8871bf4f-7fcc-45fd-bb9d-6a51b53d0844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'attentive_creative' and @title = 'Sign Up via Text for Offers' and @src = 'https://creatives.attn.tv/creatives-dynamic/multiPage/index.html']</value>
      <webElementGuid>67cfb3d2-806a-40cd-b074-573fccc6421a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
