<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Chanel Pre-owned</name>
   <tag></tag>
   <elementGuidId>4f0b8775-04f2-4fda-8dac-cc815d268347</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[2]/section[2]/div[2]/a/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.fredhopperItem-brand-1mr</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c4e23ce6-e4ed-40d5-998f-963d2bb45db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperItem-brand-1mr</value>
      <webElementGuid>d391e5e9-7481-48d4-9e39-961e9d2d78d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chanel Pre-owned</value>
      <webElementGuid>71ebe12f-8f3a-46bd-a489-148668f2ab4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4 fredhopper-noBreadcrumbs-3g1&quot;]/div[@class=&quot;fredhopper-content-boK&quot;]/section[2]/div[@class=&quot;fredhopper-item-list-root fredhopperItems-fredhopperItems-2di&quot;]/a[@class=&quot;fredhopper-item-root&quot;]/div[@class=&quot;Stack-stack-1rt fredhopperItem-meta-3F3 Stack-stackMedium-2TH&quot;]/div[1]/p[@class=&quot;fredhopperItem-brand-1mr&quot;]</value>
      <webElementGuid>4368e267-c1d6-4f3c-9147-4cabae03c5d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/section[2]/div[2]/a/div[2]/div/p</value>
      <webElementGuid>c879f5eb-c726-4fed-a554-8d03f1470041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items 1 - 48 of 81'])[2]/following::p[1]</value>
      <webElementGuid>47f12b91-6f24-4d6e-8fbc-fdda97619d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[9]/following::p[1]</value>
      <webElementGuid>2cf15e65-104d-418b-bd6b-482b9a98b550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vintage Chanel Caviar Choco Bar Shoulder Bag Black'])[1]/preceding::p[1]</value>
      <webElementGuid>0ef4c297-0ab0-440e-8f02-929432f2fb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£2,114.00'])[1]/preceding::p[1]</value>
      <webElementGuid>bb1419ea-d187-4dfb-adf2-e0ff7c1b0adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>12eabed1-8fa0-4029-ae31-cca716027ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Chanel Pre-owned' or . = 'Chanel Pre-owned')]</value>
      <webElementGuid>38e3222e-399a-41d5-9d4c-2dc364eac68d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
