<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_TED BAKER OUTLET</name>
   <tag></tag>
   <elementGuidId>1ab1e05b-2610-4efd-b4d7-b5632a4f30e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='hero']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hero</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c0369358-33af-4c90-87fe-0edf5aa3a430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hero</value>
      <webElementGuid>ae6ea67b-0d05-4bf6-99f5-e8674a6d134e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TED BAKER OUTLET</value>
      <webElementGuid>4097961e-6999-4afa-8366-6f88344b2684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;cms-root&quot;]/div[@class=&quot;row-contained-9Ys row-root-3E7&quot;]/div[1]/div[@class=&quot;columnGroup-root-1tm&quot;]/div[@class=&quot;column-root-2pW pagebuilder-column bannerleft&quot;]/div[@class=&quot;html-root-2b- uxtracking-FEATUREBOX1_tedbaker&quot;]/a[1]/h2[@id=&quot;hero&quot;]</value>
      <webElementGuid>30932f15-409e-4a7d-ab19-42d1b1162861</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='hero']</value>
      <webElementGuid>a6b40d83-720f-4ce7-84e0-a1238283492a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[3]/div/div/div/div/div/a/h2</value>
      <webElementGuid>a0d0b7d3-53b9-467b-b361-1ac729e17bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trusted by 11,000+ on Trustpilot'])[1]/following::h2[1]</value>
      <webElementGuid>02ef3c90-a86f-41cd-9755-7993418d7365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extended Christmas Returns until 31st January'])[1]/following::h2[1]</value>
      <webElementGuid>7284be47-a67e-4a01-8961-de51318fcf35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIESEL'])[1]/preceding::h2[1]</value>
      <webElementGuid>177473f7-fe7f-427b-bfab-fd1ea76eea6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GANT'])[1]/preceding::h2[2]</value>
      <webElementGuid>7172dae4-71cd-41f6-b3f2-2672d3c2d07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TED BAKER OUTLET']/parent::*</value>
      <webElementGuid>68ca653c-39ef-4cac-98cf-5f391cb3a96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>eec033d2-d184-4d26-bfa3-d554ef47e1c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'hero' and (text() = 'TED BAKER OUTLET' or . = 'TED BAKER OUTLET')]</value>
      <webElementGuid>87d7567b-6be7-4d12-a069-3a1dd43303c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
