<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Trusted by 11,000 on Trustpilot_left</name>
   <tag></tag>
   <elementGuidId>791c4d44-5435-4d52-9cbe-973ececa28bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[2]/div/div/div[2]/figure/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>701f51de-7eca-458d-af1c-15393ecac1e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>left</value>
      <webElementGuid>fd5a07d9-3d69-4813-b4d9-ec03f919b89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.secretsales.com/wysiwyg/menslp-uk.jpg</value>
      <webElementGuid>d57d945c-1c02-493d-9cdd-601650c28e12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>men</value>
      <webElementGuid>109ca61f-a3cb-4120-91ea-d7a192c2cb87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;cms-root&quot;]/div[@class=&quot;row-contained-9Ys row-root-3E7&quot;]/div[1]/div[@class=&quot;html-root-2b- uxtracking-HERO1_shopnow&quot;]/figure[@class=&quot;full-width1&quot;]/a[1]/picture[1]/img[@class=&quot;left&quot;]</value>
      <webElementGuid>dcefa6a3-644c-4d83-857c-08a77f86ec69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[2]/div/div/div[2]/figure/a/picture/img</value>
      <webElementGuid>126c105a-f292-4782-879a-8e3ba093f103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='men']</value>
      <webElementGuid>4aa9387b-5bed-4b1e-817a-8b75b14487f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>64a24a2b-2be8-4808-b453-b9725f02ee72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.secretsales.com/wysiwyg/menslp-uk.jpg' and @alt = 'men']</value>
      <webElementGuid>1fe42145-6523-4f56-ac2a-6ce607080249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
