<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select a size3-4Y4-5Y5-6Y7-8Y_66d72c</name>
   <tag></tag>
   <elementGuidId>be02190c-2a09-49fb-8dbe-569642741069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>86fc52d2-a706-4a05-9074-7c6040ce90c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>12fcf900-0deb-4d60-9258-7ca6c3ea8078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>b0bd3289-e957-4c88-97fc-5a3c41e634f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>c71ad643-08f0-4fb3-b304-64334ac8a7e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select a size3-4Y4-5Y5-6Y7-8Y9-10Y11-12Y13-14Y15-16Y</value>
      <webElementGuid>2f3b28d3-9d81-4c79-93ff-6a2917ce51d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size&quot;)</value>
      <webElementGuid>6add0139-2092-4935-983f-e1f1826a5248</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size']</value>
      <webElementGuid>ebbaa009-1439-4c9b-adbd-92f458f288f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/div/form/section/section/div/div/span/span/select</value>
      <webElementGuid>3367fb52-7c19-4572-b29a-9461a8dd36ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[1]</value>
      <webElementGuid>4b470b46-5027-4f04-9d76-5ed6aa5360e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Colour: Grey'])[1]/following::select[1]</value>
      <webElementGuid>fe6cd6b5-b914-4d78-8b6d-a14f33a2f5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::select[1]</value>
      <webElementGuid>1c3201c5-471e-41b4-b22f-f17d68599f86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[2]</value>
      <webElementGuid>fbeb063f-9d39-442f-ab80-4de2c8e3abf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>be9da4bb-cb55-453f-9202-5836d94ed304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size' and @name = 'size' and (text() = 'Please select a size3-4Y4-5Y5-6Y7-8Y9-10Y11-12Y13-14Y15-16Y' or . = 'Please select a size3-4Y4-5Y5-6Y7-8Y9-10Y11-12Y13-14Y15-16Y')]</value>
      <webElementGuid>effe8985-8c2b-42f6-931e-3776002b1cb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
