<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_OUR OTHER ACTIONS_image-img-L2s</name>
   <tag></tag>
   <elementGuidId>d7d79ca5-25fe-4029-bcd0-d926cec8c0fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div[2]/figure/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0dcd5dd8-a99c-4a86-9d88-ccab75b1eb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-img-L2s</value>
      <webElementGuid>595e1833-8f1b-498e-ad3a-690a11af2630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.secretsales.com/cdn-cgi/image/quality=85,format=auto/https://media.secretsales.com/wysiwyg/OUR_FOREST_3.jpg</value>
      <webElementGuid>422935a8-f5b4-41be-a547-ce138d360c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>4a380207-d917-4bf1-8512-685f24793335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;cms-root&quot;]/div[@class=&quot;row-contained-9Ys row-root-3E7&quot;]/div[1]/div[@class=&quot;columnGroup-root-1tm&quot;]/div[@class=&quot;column-root-2pW pagebuilder-column&quot;]/figure[1]/picture[1]/img[@class=&quot;image-img-L2s&quot;]</value>
      <webElementGuid>5185c23c-63d9-4f05-ac9b-373b74989cc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[5]/div/div/div[2]/div[2]/figure/picture/img</value>
      <webElementGuid>1f99a6b2-7cbb-4d36-9c45-f2a77209e40b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.secretsales.com/cdn-cgi/image/quality=85,format=auto/https://media.secretsales.com/wysiwyg/OUR_FOREST_3.jpg')]</value>
      <webElementGuid>129038d3-7cbb-4e5f-ac87-2aae46ba12ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/figure/picture/img</value>
      <webElementGuid>6ee5bfba-b10b-4907-a597-9060408ef3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.secretsales.com/cdn-cgi/image/quality=85,format=auto/https://media.secretsales.com/wysiwyg/OUR_FOREST_3.jpg']</value>
      <webElementGuid>ffe458a4-4a47-41c6-8cc8-9359bcf4e302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
