<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_12345</name>
   <tag></tag>
   <elementGuidId>76e65357-e183-48c6-9146-138dc97479c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='3b2edf47-657b-4da1-b3df-314a7c3a0a31']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3b2edf47-657b-4da1-b3df-314a7c3a0a31</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>56b2a35c-99a4-4f22-bed7-c74d95246a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>229a2fec-b9ba-4c95-8164-9d28ab8ceffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3b2edf47-657b-4da1-b3df-314a7c3a0a31</value>
      <webElementGuid>5eec4e49-37f9-4d68-8d6f-af89b0479486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>quantity</value>
      <webElementGuid>94a64c22-a995-4eed-a9a5-3092e431898c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345</value>
      <webElementGuid>87ee0329-36f6-4816-aa36-91230a6aa537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3b2edf47-657b-4da1-b3df-314a7c3a0a31&quot;)</value>
      <webElementGuid>b20bed84-7505-476c-b9ea-74e1997a589b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='3b2edf47-657b-4da1-b3df-314a7c3a0a31']</value>
      <webElementGuid>149ecb7e-51e0-480e-b724-cbc767848064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[2]/div/form/section/section/div[2]/div/span/span/select</value>
      <webElementGuid>df94e575-990d-436e-92e1-a5666f0a9476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/following::select[1]</value>
      <webElementGuid>a8596f9b-fa79-4845-ae23-c2f386409bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[2]</value>
      <webElementGuid>67b1f554-8efd-48d7-9417-b89f5a061e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[1]</value>
      <webElementGuid>e6fb9952-4c97-4db1-a1a4-53b4db42b6e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/preceding::select[1]</value>
      <webElementGuid>5fb869f9-5e44-4249-a71a-d534b10e4873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/span/select</value>
      <webElementGuid>6669839b-7e3e-4659-a868-c41dc7e14f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '3b2edf47-657b-4da1-b3df-314a7c3a0a31' and @name = 'quantity' and (text() = '12345' or . = '12345')]</value>
      <webElementGuid>2242de18-5adc-411d-b9d5-d1d3c786f3e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
