<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , attentive_creative, , _24add5</name>
   <tag></tag>
   <elementGuidId>bf462cab-ad9c-49a9-9943-9d1398fff77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='attentive_creative']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attentive_creative</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>56fe6de6-c99f-4c6e-bce1-678d6093b2dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>5dd11193-e1eb-42b5-a20f-dbcffa6e599e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attentive_creative</value>
      <webElementGuid>5593d656-aea5-49ea-9202-95c5b993d493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign Up via Text for Offers</value>
      <webElementGuid>2d6c89d2-0467-4114-ab52-81aeb9b55842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://creatives.attn.tv/creatives-dynamic/multiPage/index.html</value>
      <webElementGuid>67294a8f-0816-4816-892d-9858c1f90c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attentive_creative&quot;)</value>
      <webElementGuid>1f62eee8-3b96-4a6c-8e96-f3dbbfca1ab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='attentive_creative']</value>
      <webElementGuid>a7b09ce3-57c2-4ab9-9116-ec4c29f71f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='attentive_overlay']/iframe</value>
      <webElementGuid>1187f57b-4c26-4c1c-bb49-1397d06fdd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/iframe</value>
      <webElementGuid>d4212ffb-d276-4020-be44-bf3f523ba4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'attentive_creative' and @title = 'Sign Up via Text for Offers' and @src = 'https://creatives.attn.tv/creatives-dynamic/multiPage/index.html']</value>
      <webElementGuid>05168b52-ce36-4822-989f-36a11c24dd3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
