<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_concat(Don, , t go yet Sign-up for 1_e5f9eb</name>
   <tag></tag>
   <elementGuidId>5d8afc17-26e5-42ac-a429-3dbaf5b062cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeIconContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#closeIconContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1330824c-188b-402c-8b64-5de6cc9e5066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeIconContainer</value>
      <webElementGuid>eaaec862-c48f-4750-aee1-60f749bf96e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>closeIcon</value>
      <webElementGuid>dd8c368d-1b20-4d1b-a78a-1fd321eee134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dismiss this popup</value>
      <webElementGuid>3b02d378-1db5-47d4-b331-577a15eb9bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attn-element-id</name>
      <type>Main</type>
      <value>9JPo</value>
      <webElementGuid>85365295-097c-470d-8f1f-a102dfb1b377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1glrhkl</value>
      <webElementGuid>bb200a86-12b8-4c6e-93ab-2f8a812f519c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeIconContainer&quot;)</value>
      <webElementGuid>bb9facfe-bd69-4f27-b32b-709c2f090e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Products/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>eb50c1c2-2d38-4b55-a8eb-faf4034ace8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeIconContainer']</value>
      <webElementGuid>d7a05f65-d3a6-4d91-97d9-ecedb3e123b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/button</value>
      <webElementGuid>e0ef1a99-7281-4a6d-a3a2-dd6182ace286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't go yet! Sign-up for 10% OFF + beat the Black Friday rush')])[1]/preceding::button[1]</value>
      <webElementGuid>7a4674c7-46a8-4728-8cbe-65e1492f4c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ Unmissable Black Friday deals'])[1]/preceding::button[1]</value>
      <webElementGuid>8765a3b7-1025-499b-be5e-a06fe4dc97e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>bbc9db66-fcc9-485a-953e-b80fb95a41f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeIconContainer']</value>
      <webElementGuid>c110f56b-e278-4fef-8d52-618c050d9ed0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
