<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_RecommendedPrice low to highPrice hi_51dbeb</name>
   <tag></tag>
   <elementGuidId>44c07eb0-4a2d-4a7d-a214-8f33759b9c56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='sortBy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sortBy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80c70128-ad33-483c-b554-83626965d2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperSort-select-3Sh select-input-1FY field-input-23y</value>
      <webElementGuid>9122a205-2057-40a9-a977-874648be2552</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sortBy</value>
      <webElementGuid>3791a352-a630-49c6-9c8c-10dc1c7e7827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sortBy</value>
      <webElementGuid>234e8574-c2d8-4caf-a0ef-54f15913eec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RecommendedPrice low to highPrice high to lowNewest inDiscount %</value>
      <webElementGuid>8d96f20a-de07-4463-949c-380517df339e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4 fredhopper-noBreadcrumbs-3g1&quot;]/div[@class=&quot;fredhopper-content-boK&quot;]/section[1]/div[@class=&quot;visuallyHiddenUntilDesktop&quot;]/div[@class=&quot;fredhopper-itemCountAndSort-2Aw&quot;]/div[@class=&quot;fredhopper-sort-1Ml&quot;]/form[@class=&quot;fredhopperSort-form-31N&quot;]/div[@class=&quot;fredhopperSort-field-16M&quot;]/div[@class=&quot;Inline-inline-1-W Inline-inlineXSmall-2fw&quot;]/span[@class=&quot;fieldIcons-root-1cS&quot;]/span[@class=&quot;fieldIcons-input-2we&quot;]/select[@id=&quot;sortBy&quot;]</value>
      <webElementGuid>89a970ee-0c29-48ec-a6a4-b6ba98e0b41d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='sortBy']</value>
      <webElementGuid>5bb206c4-fcd3-4a62-ada8-6212bcf5fc5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/section/div/div/div[2]/form/div/div/span/span/select</value>
      <webElementGuid>edcfeac3-dd9e-4d40-b8ea-0004c0859f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[1]/following::select[1]</value>
      <webElementGuid>a0f14b92-b708-4281-880f-d06ea40b9872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items 1 - 48 of 10296'])[1]/following::select[1]</value>
      <webElementGuid>ccd1935c-16e8-4aa6-9386-e926ced21603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort By'])[2]/preceding::select[1]</value>
      <webElementGuid>0fec76ea-a3cb-42da-a678-683e9e088d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>63d5ded5-e591-47e1-a82f-81cfed997769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'sortBy' and @name = 'sortBy' and (text() = 'RecommendedPrice low to highPrice high to lowNewest inDiscount %' or . = 'RecommendedPrice low to highPrice high to lowNewest inDiscount %')]</value>
      <webElementGuid>5f645967-5b2f-443f-b4f9-9e432cc5c81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items 1 - 48 of 13823'])[1]/following::select[1]</value>
      <webElementGuid>a8494fdb-a8ae-41de-aa5f-48953247eb5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
