<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select a sizeSmallMediumLargeX-Large</name>
   <tag></tag>
   <elementGuidId>14ab8c53-64fa-4b78-98a5-6bf02f806d5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3f78a6f4-7df3-4671-97e1-8cee97965c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>3ab1f081-d1e5-4b8f-9a07-818257a9710a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>c8e05b4a-00f6-443d-8df4-444cb67f56a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>ac868ceb-6808-48e3-82f8-3a7673a13f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select a sizeSmallMediumLargeX-Large</value>
      <webElementGuid>9af6bae6-f18e-4216-8064-8d498fd7fe14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size&quot;)</value>
      <webElementGuid>33b0685d-b502-4ffc-a889-6c5b7d5cd87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size']</value>
      <webElementGuid>ef522145-b736-4dcc-84f1-0dd04c9fcb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/div/form/section/section/div/div/span/span/select</value>
      <webElementGuid>8ae2c914-4371-4df1-b4b0-48905133e1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[1]</value>
      <webElementGuid>897796d9-c378-459b-bf90-7a5bec4d5c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate your size'])[1]/following::select[1]</value>
      <webElementGuid>7f73eff6-d8d7-495b-8c70-1804ba4fdf63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::select[1]</value>
      <webElementGuid>3edeb561-71e5-4b5c-93bb-898d3a52f319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[2]</value>
      <webElementGuid>a4d4a322-618f-4ef4-81c1-1a4c9a33ed04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b10f5ad7-c10b-4ad2-a560-e83a9edcd7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size' and @name = 'size' and (text() = 'Please select a sizeSmallMediumLargeX-Large' or . = 'Please select a sizeSmallMediumLargeX-Large')]</value>
      <webElementGuid>0f26483c-5628-4eea-b518-9e841a82895a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
