<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please select a sizeSmallMediumLarge_1b6ef4</name>
   <tag></tag>
   <elementGuidId>8a6c9fa7-e5b0-489f-bfa3-36723f09724c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='size']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#size</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0cef4675-d7b4-4e1d-9537-81b10a7b1fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-input-1lN Select-select-3Zm</value>
      <webElementGuid>27c6129a-b38d-4fdc-a0ac-e64d06a80b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>1fae82dc-9942-4ac2-bb59-bfda2787061f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>size</value>
      <webElementGuid>2f0279fa-c4e6-434e-a97d-7c0af265e29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select a sizeSmallMediumLargeX-Large2XL</value>
      <webElementGuid>7a8932d6-b937-41a7-8dcc-4083fe24c491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;size&quot;)</value>
      <webElementGuid>b8f79163-102f-493c-898b-e39c299acdf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='size']</value>
      <webElementGuid>796650cf-79ba-4d8e-a043-c71c4f80acf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/div/form/section/section/div/div/span/span/select</value>
      <webElementGuid>0750f08d-98e3-4c02-9d79-26fc498e595e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::select[1]</value>
      <webElementGuid>1383bab0-e3e6-4170-b821-06a29d756270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Calculate your size'])[1]/following::select[1]</value>
      <webElementGuid>69efbbfd-7257-48f2-ba2d-721adc5b263c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[1]/preceding::select[1]</value>
      <webElementGuid>b4393741-e640-49bf-87d8-a3cd0f45e3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Bag'])[1]/preceding::select[2]</value>
      <webElementGuid>8baf35db-a24e-40a1-805c-4ad8337e6b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>22f3b73e-aebe-46d1-92be-30e093d26fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'size' and @name = 'size' and (text() = 'Please select a sizeSmallMediumLargeX-Large2XL' or . = 'Please select a sizeSmallMediumLargeX-Large2XL')]</value>
      <webElementGuid>de2e22b7-5c6d-46a9-a348-e4955b677f3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
