<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add To Cart</name>
   <tag></tag>
   <elementGuidId>f23dfdb6-50d4-47c7-bda7-2425dd78a6d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_17_2_1_1699532695744_187']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sqs-add-to-cart-button-inner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bedd291a-a23c-4a5a-8fcc-f37663592f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sqs-add-to-cart-button-inner</value>
      <webElementGuid>c3a6cd44-5a88-4ea5-ac4e-14b5659db329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Cart</value>
      <webElementGuid>bfaf927f-55eb-4662-94f5-979426ba5da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1699532695744_187&quot;)/div[@class=&quot;sqs-add-to-cart-button-inner&quot;]</value>
      <webElementGuid>141e4048-5dbc-403a-9bbd-0316d61e4bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1699532695744_187']/div</value>
      <webElementGuid>0889bb62-15eb-42dc-88fc-09126434c48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::div[3]</value>
      <webElementGuid>15f265d7-0541-49aa-ad18-a981c5579ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HAIR ELIXIR - 100ML'])[3]/preceding::div[1]</value>
      <webElementGuid>945d20cf-b076-4c58-b4e6-9899d42917c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from £53.00'])[1]/preceding::div[3]</value>
      <webElementGuid>b255ef31-8c01-4b9b-bc65-594ed9026e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add To Cart']/parent::*</value>
      <webElementGuid>8099acd9-bb79-4942-a1ec-8b5783706673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>d130f5bc-74f1-41a1-9979-19c2a9245446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add To Cart' or . = 'Add To Cart')]</value>
      <webElementGuid>1ff917e8-ce27-4939-8127-5603db08c22c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
