<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_21.00</name>
   <tag></tag>
   <elementGuidId>0b5b4f34-5b26-48df-8839-4241e9e31ee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div/div[3]/section[2]/div[2]/a/div[2]/div[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fredhopperItemPrices-fredhopperItemPricesCurrentPrice-28v</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d0ff11d-0308-472d-adf5-f0fdd9773f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fredhopperItemPrices-fredhopperItemPricesCurrentPrice-28v</value>
      <webElementGuid>b9929372-09fa-499f-8859-3584f0d73024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£21.00</value>
      <webElementGuid>8a65245d-7b58-4cc7-8656-97aa966a6676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;container fredhopper-fredhopper-3i4&quot;]/div[@class=&quot;fredhopper-content-boK&quot;]/section[2]/div[@class=&quot;fredhopper-item-list-root fredhopperItems-fredhopperItems-2di&quot;]/a[@class=&quot;fredhopper-item-root&quot;]/div[@class=&quot;Stack-stack-1rt fredhopperItem-meta-3F3 Stack-stackMedium-2TH&quot;]/div[@class=&quot;Inline-inline-1-W fredhopperItemPrices-fredhopperItemPrices-1oK Inline-alignItemsCenter-3Z5&quot;]/span[@class=&quot;fredhopperItemPrices-fredhopperItemPricesCurrentPrice-28v&quot;]</value>
      <webElementGuid>f6c4f1a3-9fff-4a42-b642-82c4e108e269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div/div[3]/section[2]/div[2]/a/div[2]/div[2]/span[2]</value>
      <webElementGuid>2a17e107-34e3-4157-b321-0278b629b101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='£50.00'])[1]/following::span[1]</value>
      <webElementGuid>f950cb5f-3a14-486a-8874-c1b6f9984118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weekday Galaxy Loose Fit Jeans In Fresh'])[1]/following::span[2]</value>
      <webElementGuid>d506ef99-5cbd-4ba0-8cf6-e1d441d5e9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::span[2]</value>
      <webElementGuid>1933673d-2f09-4621-bbdf-5e8380306cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='£21.00']/parent::*</value>
      <webElementGuid>65f1bde2-aa98-4b52-86b0-89c19dbcdf13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span[2]</value>
      <webElementGuid>3cbf3c5d-fe84-4139-90f7-3384604b7b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '£21.00' or . = '£21.00')]</value>
      <webElementGuid>0eb4db4e-10d2-450a-a612-f5fc70a3ca09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
