<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Men</name>
   <tag></tag>
   <elementGuidId>d39e715b-08a9-4387-8148-921d59bc6df0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/aside[4]/div/div/div/div/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.c-mobile-nav__categories.js-mobile-nav-category > li:nth-of-type(4) > a.c-mobile-nav__nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cda867e7-e758-4d16-b53e-7242a29d2e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.secretsales.com/shop/homeware/</value>
      <webElementGuid>76e49447-3b6c-46aa-b810-baf6551865e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-mobile-nav__nav-link</value>
      <webElementGuid>89c8f105-35fb-470a-9600-9e1b95d1aba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Men</value>
      <webElementGuid>adfa283c-5cd5-4175-8e21-58c98d861910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/aside[@class=&quot;navigation-root_open-3KH navigation-root-3v2 navigation-exit-2Xc navigation-hidden-1Ft navigation-enter-1rs navigation-visible-1M_&quot;]/div[@class=&quot;navigation-body-1TM navigation-exit-2Xc navigation-visible-1M_&quot;]/div[1]/div[@class=&quot;cmsBlock-content-_Ac&quot;]/div[1]/div[@class=&quot;html-root-2b-&quot;]/ul[@class=&quot;c-mobile-nav__categories js-mobile-nav-category&quot;]/li[4]/a[@class=&quot;c-mobile-nav__nav-link&quot;]</value>
      <webElementGuid>92e24442-bdee-42ed-b1bb-7c7acac1a5ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/aside[4]/div/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>a2477928-eeb9-4f8e-afd1-6f72266306a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Men')])[7]</value>
      <webElementGuid>58bdf97b-29ef-4836-9764-780c37881954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Sunglasses Shop'])[2]/following::a[1]</value>
      <webElementGuid>478fb9b2-8a7f-4be2-a32f-b4f820f1cfa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Curve Edit'])[2]/following::a[2]</value>
      <webElementGuid>de5744bb-0705-4bcb-8843-352ca91ff8e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men'])[30]/preceding::a[2]</value>
      <webElementGuid>3adf2e5f-b1d3-4ac4-a51a-78cee611e451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop All'])[36]/preceding::a[3]</value>
      <webElementGuid>2b5198bd-5007-43ac-a5f0-9c3cfbe50ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.secretsales.com/shop/homeware/')]</value>
      <webElementGuid>51278b43-ff36-4bab-b1bf-8aceae499270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside[4]/div/div/div/div/div/ul/li[4]/a</value>
      <webElementGuid>0b102b95-3146-49d2-9801-a2a4da8ad5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.secretsales.com/shop/homeware/' and (text() = 'Men' or . = 'Men')]</value>
      <webElementGuid>94ff381a-02a8-4851-a853-163ac9f768fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
