<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Outlet</name>
   <tag></tag>
   <elementGuidId>0976633f-1122-474e-8f75-6ab644e57951</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.c-navigation__categories > li:nth-of-type(9) > a.c-ev-attached</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/header/div[3]/div/div/nav/div/div/div/div/div/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>efb79e6b-3309-4776-9de9-c64e8e3e2c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.secretsales.com/browse/products/shop-by/discount_percentage_gb/0.69%3Cdiscount_percentage_gb%3C1.0/</value>
      <webElementGuid>e11ad483-a74b-4498-bdac-11117facf713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-ev-attached</value>
      <webElementGuid>ae2f4333-8191-4e16-bf57-e0a9c1fd2180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outlet</value>
      <webElementGuid>c289d6de-1792-4fb1-9cb6-5db9891a40b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/header[@class=&quot;header-root header-root-2P7&quot;]/div[@class=&quot;container header-content-BBd&quot;]/div[@class=&quot;header-actionsWrapper-1gF&quot;]/div[@class=&quot;header-store-nav header-primaryActions-2bB&quot;]/nav[@class=&quot;visuallyHiddenUntilDesktop&quot;]/div[@class=&quot;header-desktopNavWrapper-S9Y&quot;]/div[@class=&quot;c-navigation__categories&quot;]/div[@class=&quot;cmsBlock-content-_Ac&quot;]/div[1]/div[@class=&quot;html-root-2b-&quot;]/ul[@class=&quot;c-navigation__categories&quot;]/li[9]/a[@class=&quot;c-ev-attached&quot;]</value>
      <webElementGuid>553301f9-3f56-404c-9f5c-7bfc522b9ec5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/header/div[3]/div/div/nav/div/div/div/div/div/ul/li[9]/a</value>
      <webElementGuid>2c18f0fb-9e1f-4aa8-8162-948334a06501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Outlet')])[4]</value>
      <webElementGuid>95d17889-0266-4115-885d-be524ac4ad42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Gift Guide'])[1]/following::a[1]</value>
      <webElementGuid>4c1cdf6a-7a91-428f-ba16-ac0395bb3bfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stocking Fillers under £10'])[1]/following::a[2]</value>
      <webElementGuid>45c58755-e9b3-46a7-b36f-14cde67b0570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Women'])[3]/preceding::a[1]</value>
      <webElementGuid>4fb75ff0-12cc-407d-a67d-dc5571d2ade8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop All'])[20]/preceding::a[1]</value>
      <webElementGuid>9244ca58-e1dc-413e-9bec-c2b48cf369ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outlet']/parent::*</value>
      <webElementGuid>f47b0785-61f9-48bf-b31c-af4bc166d8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.secretsales.com/browse/products/shop-by/discount_percentage_gb/0.69%3Cdiscount_percentage_gb%3C1.0/')]</value>
      <webElementGuid>ccab2f7d-a074-4cee-9f05-6728df67d9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>cf33918f-dd59-48ef-8aee-d6de25af39d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.secretsales.com/browse/products/shop-by/discount_percentage_gb/0.69%3Cdiscount_percentage_gb%3C1.0/' and (text() = 'Outlet' or . = 'Outlet')]</value>
      <webElementGuid>4209dbca-5abb-44db-b93f-3e5777d2d75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop All'])[19]/preceding::a[1]</value>
      <webElementGuid>9bb57a98-c44b-441c-b844-3efbd7b5ba77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
