<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign-up for 10 OFF  beat the Black F_ef6a2e</name>
   <tag></tag>
   <elementGuidId>fe4aa8fb-eaca-4286-88ba-6bb35aa03770</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeIconContainer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeIconContainer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>979f177c-6e64-40dc-b896-9f8917710b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeIconContainer</value>
      <webElementGuid>0da76252-77e2-43e3-bf25-95e80ac635bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>closeIcon</value>
      <webElementGuid>9572f4e9-0c6a-48c3-ab94-9faadf18d468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dismiss this popup</value>
      <webElementGuid>e90e0856-ada5-467a-9148-821645ec5b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attn-element-id</name>
      <type>Main</type>
      <value>LdTJ</value>
      <webElementGuid>1b6b6326-6e46-4fff-a682-b394d3d7bbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1glrhkl</value>
      <webElementGuid>f1467e2d-da6a-487e-bc1d-eb6de396773c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeIconContainer&quot;)</value>
      <webElementGuid>65215978-b946-42f7-923f-43c4739a54f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SECRET SALES  OH, HELLO BLACK FRIDAY  _0edd18/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>93587286-f1c9-4fd7-9686-424fc061a6f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeIconContainer']</value>
      <webElementGuid>d08f5210-1c37-4e99-b96f-2d338b30d84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/button</value>
      <webElementGuid>3179866b-9779-42d3-a58a-f29cf4026f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-up for 10% OFF + beat the Black Friday rush'])[1]/preceding::button[1]</value>
      <webElementGuid>82856999-10bc-4c01-bd9c-161849616ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ Unmissable Black Friday deals'])[1]/preceding::button[1]</value>
      <webElementGuid>28aa929d-8953-4cc8-8913-7ac111aef226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6e6535c3-1c12-4ae9-a19b-5d7abf6c8f2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeIconContainer']</value>
      <webElementGuid>13b5f360-b0cb-4ce7-9432-233d0883dcef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
