<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign-up for 10 OFF  beat the Black F_ef6a2e</name>
   <tag></tag>
   <elementGuidId>0539c68f-13b1-49ff-a6d9-52a4f940f186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeIconContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#closeIconContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88262dfe-7017-43e3-aa05-26d59200830a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeIconContainer</value>
      <webElementGuid>e1e491c6-75fe-489e-bb78-2632d3eabcdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>closeIcon</value>
      <webElementGuid>9429f052-31d3-4da3-8ac9-8d78842dbc01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dismiss this popup</value>
      <webElementGuid>111b9ebb-e167-425a-9d2c-bff4e4186c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attn-element-id</name>
      <type>Main</type>
      <value>LdTJ</value>
      <webElementGuid>c40508bf-2829-4cb1-b915-6313a6b4a53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-1glrhkl</value>
      <webElementGuid>41bd3b1d-fbcb-4fec-8c94-d9a5dcc9c615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeIconContainer&quot;)</value>
      <webElementGuid>1c9bcb5a-01d5-4a0f-98cb-44bd9c26e962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_SECRET SALES  OH, HELLO BLACK FRIDAY  _0edd18/iframe_concat(id(, , attentive_creative, , _24add5</value>
      <webElementGuid>d8b6eb1b-c48e-4ff2-a5f3-40a863bf5748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeIconContainer']</value>
      <webElementGuid>2aa9aafc-1964-4bd6-8e4c-7e3bd580afec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/button</value>
      <webElementGuid>95c148af-ce1a-431c-a0b6-b73971d1b896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign-up for 10% OFF + beat the Black Friday rush'])[1]/preceding::button[1]</value>
      <webElementGuid>3e0a282d-3187-4036-96f7-0136d0f760bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ Unmissable Black Friday deals'])[1]/preceding::button[1]</value>
      <webElementGuid>cc5ece88-c10d-4372-b249-02813a696509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>efb4676d-66d8-4c36-a889-abad8a1bdf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeIconContainer']</value>
      <webElementGuid>49e2d42d-ea60-4a75-90ff-d1c79c054c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
