<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a1e2c63a-34c5-4a7c-8ca9-35ae31f06a0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div[2]/div[4]/div/div/div/div/div/div/div/span[2]/div[5]/figure/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(2) > div.orb > figure.uxtracking_HPlogo5 > a > img[alt=&quot;calvin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ab37e271-6366-40d8-b870-c042fca7d4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.secretsales.com/wysiwyg/ck.jpg</value>
      <webElementGuid>7e520c8e-0f18-472e-8e29-665bcc9cfb99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>calvin</value>
      <webElementGuid>7408baaa-91dc-4204-bd42-c6d84e1f4d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>417px</value>
      <webElementGuid>5b027a48-dda5-4e3a-83a1-cc92baaa0527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>222</value>
      <webElementGuid>c7d26b3b-4788-4763-b873-02ba4fc7d16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[@class=&quot;main-root-2Er&quot;]/div[@class=&quot;cms-block-container-root&quot;]/div[@class=&quot;cms-root&quot;]/div[@class=&quot;row-contained-9Ys row-root-3E7&quot;]/div[1]/div[@class=&quot;html-root-2b-&quot;]/div[@class=&quot;pwalogo-marginhp&quot;]/div[1]/div[@class=&quot;marquee&quot;]/div[@class=&quot;marquee--inner&quot;]/span[2]/div[@class=&quot;orb&quot;]/figure[@class=&quot;uxtracking_HPlogo5&quot;]/a[1]/img[1]</value>
      <webElementGuid>415b4787-4b20-4bf6-b6c5-91a762561887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div[2]/div[4]/div/div/div/div/div/div/div/span[2]/div[5]/figure/a/img</value>
      <webElementGuid>21884113-e0be-416d-bd0d-d79634e8d141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='calvin'])[2]</value>
      <webElementGuid>9c6ccbde-b953-4493-ba4f-8b2ba6aceabe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div[5]/figure/a/img</value>
      <webElementGuid>7f6796f8-a21c-4b41-a743-041aff84f87e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.secretsales.com/wysiwyg/ck.jpg' and @alt = 'calvin']</value>
      <webElementGuid>63408e57-33e6-44e6-8edc-01ce8fd2cdeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
