<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add To Cart</name>
   <tag></tag>
   <elementGuidId>c5daac87-2385-469e-8dba-0bedebf50251</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sqs-add-to-cart-button-inner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='yui_3_17_2_1_1699619231016_187']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a8381b3-995b-4713-b097-13bd0699dc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sqs-add-to-cart-button-inner</value>
      <webElementGuid>19e37e6f-0f24-4601-9928-f42f9b672bbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add To Cart</value>
      <webElementGuid>fd9d7da6-0855-4fb3-83fe-f8ad16be49fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yui_3_17_2_1_1699619231016_187&quot;)/div[@class=&quot;sqs-add-to-cart-button-inner&quot;]</value>
      <webElementGuid>072248e1-81d6-4d15-b9bb-432d4266070b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_3_17_2_1_1699619231016_187']/div</value>
      <webElementGuid>bc9d0a29-d862-43f9-ba14-3212c8a605cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantity:'])[1]/following::div[3]</value>
      <webElementGuid>dafa6c1e-1c3b-43d8-a55c-e3bba00bd0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BEARD OIL WITH SANDALWOOD &amp; NEROLI'])[3]/preceding::div[1]</value>
      <webElementGuid>ad793d13-0fd6-4fe1-b15e-114ce7dc05e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='from £42.00'])[1]/preceding::div[2]</value>
      <webElementGuid>db3b6db6-60f6-4614-be1d-15b04ed359a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add To Cart']/parent::*</value>
      <webElementGuid>cbe7feb9-68b2-4bf5-a209-710025b2d490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div</value>
      <webElementGuid>686795fd-c7c4-4d0d-9d5c-39d4b58e6128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add To Cart' or . = 'Add To Cart')]</value>
      <webElementGuid>eb89250f-b36d-4856-b68d-4373f05e5b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
